'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const image=fs.readFileSync(path.join(root,'assets/entry/first-login-v1.png'));
assert.equal(image.subarray(0,8).toString('hex'),'89504e470d0a1a0a','Approved image must be a PNG');
assert.equal(image.readUInt32BE(16),941,'Approved artwork width changed');
assert.equal(image.readUInt32BE(20),1672,'Approved artwork height changed');
assert(image.length>200000,'Only the exact full-resolution artwork may be used');
const code=read('side-games/neon-entry-v1.js');
const css=read('side-games/neon-entry-v1.css');
const auth=read('side-games/neon-entry-auth-v1.js');
const index=read('index.html');
assert(code.includes("new URL('./assets/entry/first-login-v1.png',document.baseURI)"),'Image asset path missing');
assert(code.includes('viewBox="0 0 941 1672"'),'Image and SVG controls must share source coordinates');
for(const action of ['google','guest','help'])assert(code.includes('data-entry-action="'+action+'"'),'Missing image control '+action);
assert(css.includes('width:min(100vw,56.2799dvh)'),'Responsive image ratio changed');
assert(css.includes('#nxEntry[hidden]'),'Signed-in screen must be hidden');
assert(auth.includes('onAuthStateChanged(auth,user=>entry.resolveAuth(user)'),'Must wait for real Firebase auth restoration');
assert(!auth.includes('signInAnonymously'),'Do not silently create guest accounts during startup');
assert(code.includes("api[method]()"),'Buttons must delegate to existing social auth implementation');
assert(code.includes("window.NEON_XI_ENTRY={"),'Welcome controller bridge missing');
assert(code.includes("if(!social?.profile"),'New accounts must see username chooser');
assert(code.includes("guide.hidden=false"),'Help button must open real guide');
for(const file of ['neon-entry-v1.css','neon-entry-v1.js','neon-entry-auth-v1.js'])assert(index.includes('./side-games/'+file+"?v='+VERSION"),'Root must load '+file);
assert(index.includes("const VERSION='20260929-welcome-v1'"),'New welcome assets require a new cache token');
new Function(code);
console.log('PASS: approved artwork resolution, pixel-aligned login controls, restored auth bypass, account reuse and guidance.');
