(() => {
  const STYLE_ID = 'neon-xi-home-hub-style';
  const styles = `
    #bootHome .neonHomeScene{--nx-lime:#9dff58;--nx-green:#52ff91;--nx-mint:#c9ffda;--nx-cyan:#58f7ff;background:radial-gradient(circle at 16% 28%,rgba(69,255,135,.1),transparent 27%),radial-gradient(circle at 84% 67%,rgba(37,220,255,.075),transparent 31%),linear-gradient(145deg,#010504 0%,#04100b 47%,#020706 100%)!important}
    #bootHome .neonHomeScene::after{content:"";position:absolute;inset:0;z-index:0;pointer-events:none;opacity:.28;background:repeating-linear-gradient(90deg,transparent 0 7.9vw,rgba(100,255,150,.055) 8vw),repeating-linear-gradient(0deg,transparent 0 7.9vw,rgba(100,255,150,.035) 8vw);mask-image:linear-gradient(180deg,transparent,black 35%,black 80%,transparent)}
    #bootHome .neonHomeStand{opacity:.22!important}#bootHome .neonHomePitchGlow{height:26vh!important;opacity:.56}
    #bootHome .neonHomeMist{width:34vw!important;height:24vh!important;opacity:.16!important;filter:blur(42px)!important;animation:nxMist 9s ease-in-out infinite alternate}#bootHome .neonHomeMistRight{animation-delay:-4s}
    #bootHome .neonHomeTopbar{padding:14px 22px 0!important}#bootHome .neonTopControl{min-height:42px!important;border-radius:12px!important;background:rgba(3,10,7,.72)!important;backdrop-filter:blur(14px)}#bootHome .neonTopIconOnly{width:42px!important}
    #bootHome .neonHomeCenterWrap{display:block!important;padding:0 22px 22px!important}#bootHome .neonHomeHero{width:min(1180px,100%)!important;height:100%;margin:0 auto;display:flex!important;flex-direction:column;gap:10px!important}
    #bootHome .neonHomeLogo{width:min(38vw,430px)!important;max-height:116px;object-fit:contain;margin:-20px auto -10px;filter:drop-shadow(0 0 18px rgba(110,255,150,.18))!important}
    #bootHome .neonHomeSubtitle{font-size:10px!important;letter-spacing:.5em!important;gap:12px!important;margin:0 auto 4px}#bootHome .neonHomeSubtitle span{width:72px!important}
    #bootHome .neonHomeMenu,#bootHome .neonHomeQuickRow,#bootHome .neonHomeFooter{display:none!important}
    #bootHome .nxHomeHub{position:relative;display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:16px;min-height:0;flex:1}
    #bootHome .nxZone{position:relative;isolation:isolate;min-width:0;overflow:hidden;border:1px solid rgba(111,255,157,.36);border-radius:24px;background:linear-gradient(145deg,rgba(5,16,11,.92),rgba(2,8,6,.96));box-shadow:inset 0 0 0 1px rgba(205,255,218,.035),inset 0 -60px 90px rgba(0,0,0,.22),0 24px 70px rgba(0,0,0,.35),0 0 34px rgba(56,255,128,.07)}
    #bootHome .nxZone::before{content:"";position:absolute;inset:-45% -20%;z-index:-2;pointer-events:none;opacity:.34;background:radial-gradient(ellipse at 30% 50%,rgba(75,255,137,.24),transparent 31%),radial-gradient(ellipse at 78% 40%,rgba(75,232,255,.1),transparent 28%);filter:blur(30px);animation:nxVapor 11s ease-in-out infinite alternate}
    #bootHome .nxZone::after{content:"";position:absolute;left:0;right:0;top:0;height:2px;z-index:3;pointer-events:none;background:linear-gradient(90deg,transparent 0%,rgba(89,255,145,.12) 15%,var(--nx-mint) 48%,white 50%,var(--nx-green) 52%,rgba(89,255,145,.12) 85%,transparent 100%);background-size:38% 100%;background-repeat:no-repeat;filter:drop-shadow(0 0 6px var(--nx-green));animation:nxCurrent 3.4s linear infinite}
    #bootHome .nxDraftZone,#bootHome .nxSideZone{display:flex;flex-direction:column;padding:26px}#bootHome .nxSideZone{background:linear-gradient(145deg,rgba(4,14,11,.94),rgba(2,9,9,.97))}
    #bootHome .nxZoneHead{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;margin-bottom:20px}.nxEyebrow{display:flex;align-items:center;gap:9px;color:var(--nx-green);font:800 10px/1 system-ui;letter-spacing:.18em;text-transform:uppercase}.nxEyebrow::before{content:"";width:19px;height:1px;background:currentColor;box-shadow:0 0 8px currentColor}
    #bootHome .nxZone h2{margin:10px 0 0;color:#f3fff6;font:900 clamp(31px,4vw,56px)/.88 system-ui;letter-spacing:-.065em;text-transform:uppercase}#bootHome .nxSideZone h2{font-size:clamp(28px,3.1vw,44px)}
    #bootHome .nxZoneCopy{max-width:440px;margin:12px 0 0;color:rgba(221,255,231,.62);font-size:12px;line-height:1.55}#bootHome .nxZoneIndex{color:rgba(157,255,88,.18);font:900 54px/1 system-ui;letter-spacing:-.08em}
    #bootHome .nxDraftModes{display:grid;gap:9px;margin-top:auto}
    #bootHome .nxDraftModes .neonHomeAction{min-height:68px!important;padding:12px 15px!important;grid-template-columns:45px minmax(0,1fr) 20px!important;gap:12px!important;border-radius:15px!important;background:rgba(3,11,7,.76)!important;border-color:rgba(115,255,159,.25)!important;box-shadow:inset 0 0 0 1px rgba(185,255,204,.025)!important}
    #bootHome .nxDraftModes .neonHomeAction:hover,#bootHome .nxDraftModes .neonHomeAction:focus-visible{border-color:rgba(164,255,191,.7)!important;background:rgba(7,23,14,.9)!important;box-shadow:0 0 24px rgba(64,255,128,.13)!important}
    #bootHome .nxDraftModes .neonHomeActionIcon{width:43px!important;height:43px!important;border-radius:12px!important}#bootHome .nxDraftModes .neonHomeActionIcon svg{width:23px!important;height:23px!important}
    #bootHome .nxDraftModes .neonHomeActionText strong{font-size:16px!important;letter-spacing:.02em!important}#bootHome .nxDraftModes .neonHomeActionText small{margin-top:4px!important;font-size:9px!important;letter-spacing:.08em!important;color:rgba(157,255,88,.74)!important}#bootHome .nxDraftModes .neonHomeActionArrow{font-size:28px!important}
    #bootHome .nxDraftUtility{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:12px;padding-top:13px;border-top:1px solid rgba(106,255,150,.12)}#bootHome .nxDraftUtility>span{color:rgba(216,255,228,.43);font-size:9px;letter-spacing:.12em;text-transform:uppercase}
    #bootHome .nxTournament{border:0;background:none;color:var(--nx-green);font-weight:800;font-size:10px;letter-spacing:.09em;cursor:pointer;padding:7px 0}
    #bootHome .nxSideGrid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:auto}
    #bootHome .nxSideGame{position:relative;display:flex;flex-direction:column;justify-content:flex-end;min-height:134px;padding:16px;overflow:hidden;text-decoration:none;color:#effff4;border:1px solid rgba(89,244,255,.19);border-radius:17px;background:linear-gradient(145deg,rgba(4,17,13,.88),rgba(2,9,9,.96));box-shadow:inset 0 0 30px rgba(47,255,135,.025);transition:transform .18s ease,border-color .18s ease,box-shadow .18s ease}
    #bootHome .nxSideGame:first-child{grid-column:span 2;min-height:152px;border-color:rgba(125,255,166,.34);background:linear-gradient(120deg,rgba(7,24,14,.94),rgba(2,10,9,.97))}
    #bootHome .nxSideGame::before{content:"";position:absolute;width:150px;height:150px;right:-52px;top:-72px;border:1px solid rgba(105,255,153,.16);border-radius:50%;box-shadow:0 0 35px rgba(68,255,133,.06),inset 0 0 34px rgba(73,255,137,.035)}
    #bootHome .nxSideGame:hover,#bootHome .nxSideGame:focus-visible{transform:translateY(-3px);border-color:rgba(173,255,197,.72);box-shadow:0 0 28px rgba(63,255,134,.13),inset 0 0 36px rgba(57,255,133,.05);outline:none}
    #bootHome .nxSideCode{position:absolute;top:14px;right:15px;color:rgba(138,255,172,.28);font:900 22px/1 system-ui}.nxSideIcon{display:grid;place-items:center;width:36px;height:36px;margin-bottom:15px;border-radius:10px;border:1px solid rgba(116,255,160,.22);color:var(--nx-green);background:rgba(8,24,14,.72);font-size:17px;box-shadow:0 0 14px rgba(67,255,132,.07)}
    #bootHome .nxSideGame strong{font-size:15px;letter-spacing:.015em}#bootHome .nxSideGame small{display:block;margin-top:5px;color:rgba(213,255,227,.5);font-size:9px;letter-spacing:.06em;text-transform:uppercase}
    #bootHome .nxAllGames{display:flex;align-items:center;justify-content:space-between;margin-top:12px;color:rgba(211,255,225,.53);font-size:10px;text-decoration:none;letter-spacing:.08em;text-transform:uppercase}#bootHome .nxAllGames b{color:var(--nx-green);font-size:18px}
    #bootHome .nxPressable{touch-action:manipulation}#bootHome .nxPressable:active,#bootHome .nxPressable.is-pressed{transform:translateY(2px) scale(.985)!important;filter:brightness(1.25);transition-duration:.06s!important}
    #bootHome .nxPulse{position:absolute;width:12px;height:12px;border:1px solid rgba(198,255,214,.9);border-radius:50%;pointer-events:none;transform:translate(-50%,-50%) scale(.2);animation:nxPulse .55s ease-out forwards;box-shadow:0 0 12px var(--nx-green)}
    @keyframes nxCurrent{from{background-position:-60% 0}to{background-position:160% 0}}@keyframes nxMist{from{transform:translate3d(-8%,2%,0) scale(.9)}to{transform:translate3d(9%,-5%,0) scale(1.18)}}@keyframes nxVapor{from{transform:translate3d(-5%,2%,0) rotate(-2deg)}to{transform:translate3d(6%,-3%,0) rotate(3deg)}}@keyframes nxPulse{to{opacity:0;transform:translate(-50%,-50%) scale(9)}}
    @media(max-width:760px){#bootHome .neonHomeTopbar{padding:8px 12px 0!important}#bootHome .neonTopLang{display:none!important}#bootHome .neonHomeCenterWrap{padding:0 11px 13px!important;overflow:auto}#bootHome .neonHomeLogo{width:min(67vw,320px)!important;max-height:76px;margin:0 auto -7px}#bootHome .neonHomeSubtitle{font-size:7px!important;margin-bottom:3px}#bootHome .neonHomeSubtitle span{width:38px!important}#bootHome .nxHomeHub{grid-template-columns:1fr;grid-template-rows:auto auto;gap:10px}#bootHome .nxZone{border-radius:19px}#bootHome .nxDraftZone,#bootHome .nxSideZone{padding:17px}#bootHome .nxZoneHead{margin-bottom:13px}#bootHome .nxZone h2{font-size:31px}#bootHome .nxSideZone h2{font-size:27px}#bootHome .nxZoneCopy{font-size:10px;margin-top:8px;line-height:1.4}#bootHome .nxZoneIndex{font-size:38px}#bootHome .nxDraftModes{grid-template-columns:repeat(3,minmax(0,1fr));gap:7px}#bootHome .nxDraftModes .neonHomeAction{display:flex!important;flex-direction:column;align-items:flex-start!important;min-height:98px!important;padding:10px!important;gap:7px!important}#bootHome .nxDraftModes .neonHomeActionIcon{width:34px!important;height:34px!important}#bootHome .nxDraftModes .neonHomeActionIcon svg{width:19px!important;height:19px!important}#bootHome .nxDraftModes .neonHomeActionText strong{font-size:10px!important}#bootHome .nxDraftModes .neonHomeActionText small{font-size:7px!important;line-height:1.2}#bootHome .nxDraftModes .neonHomeActionArrow{display:none}#bootHome .nxDraftUtility{margin-top:8px;padding-top:8px}#bootHome .nxSideGrid{grid-template-columns:repeat(3,minmax(0,1fr));gap:7px}#bootHome .nxSideGame,#bootHome .nxSideGame:first-child{grid-column:auto;min-height:100px;padding:11px;border-radius:13px}#bootHome .nxSideIcon{width:29px;height:29px;margin-bottom:9px;font-size:14px}#bootHome .nxSideGame strong{font-size:10px;line-height:1.1}#bootHome .nxSideGame small{font-size:7px;line-height:1.2}#bootHome .nxSideCode{font-size:16px;top:10px;right:10px}#bootHome .nxAllGames{margin-top:9px;font-size:8px}}
    @media(max-width:760px){
      #bootHome .neonHomeCenterWrap{padding-bottom:10px!important}
      #bootHome .nxHomeHub{min-height:calc(100dvh - 140px);grid-template-rows:minmax(0,1fr) minmax(0,1fr);gap:11px}
      #bootHome .nxDraftZone,#bootHome .nxSideZone{padding:18px 17px}
      #bootHome .nxZoneHead{margin-bottom:14px}
      #bootHome .nxEyebrow{font-size:9px;letter-spacing:.16em}
      #bootHome .nxZone h2{font-size:33px}
      #bootHome .nxSideZone h2{font-size:29px}
      #bootHome .nxZoneCopy{display:block;font-size:10px;line-height:1.4;margin-top:7px;max-width:310px}
      #bootHome .nxDraftModes .neonHomeAction{min-height:112px!important;padding:12px 10px!important;gap:9px!important}
      #bootHome .nxDraftModes .neonHomeActionIcon{width:38px!important;height:38px!important}
      #bootHome .nxDraftModes .neonHomeActionIcon svg{width:21px!important;height:21px!important}
      #bootHome .nxDraftModes .neonHomeActionText strong{font-size:11px!important;line-height:1.1!important}
      #bootHome .nxDraftModes .neonHomeActionText small{font-size:8px!important;line-height:1.25!important}
      #bootHome .nxDraftUtility{margin-top:10px;padding-top:10px}
      #bootHome .nxTournament{font-size:11px;padding:8px 0}
      #bootHome .nxSideGame,#bootHome .nxSideGame:first-child{min-height:122px;padding:12px}
      #bootHome .nxSideIcon{width:34px;height:34px;margin-bottom:11px;font-size:16px}
      #bootHome .nxSideGame strong{font-size:11px;line-height:1.15}
      #bootHome .nxSideGame small{font-size:8px;line-height:1.3;margin-top:6px}
      #bootHome .nxSideCode{font-size:18px}
      #bootHome .nxAllGames{font-size:9px;margin-top:11px}
    }
    @media(max-width:430px){#bootHome .nxDraftUtility>span{display:none}}
    @media(max-height:720px) and (max-width:760px){#bootHome .nxHomeHub{min-height:560px;grid-template-rows:auto auto}#bootHome .nxZoneCopy{display:none}#bootHome .nxDraftModes .neonHomeAction{min-height:102px!important}#bootHome .nxSideGame,#bootHome .nxSideGame:first-child{min-height:108px}}
    @media(prefers-reduced-motion:reduce){#bootHome .nxZone::before,#bootHome .nxZone::after,#bootHome .neonHomeMist{animation:none!important}#bootHome .nxPressable{transition:none!important}}
  `;
  const addStyles=()=>{if(document.getElementById(STYLE_ID))return;const style=document.createElement('style');style.id=STYLE_ID;style.textContent=styles;document.head.appendChild(style)};
  const card=(href,code,icon,title,subtitle)=>`<a class="nxSideGame nxPressable" href="${href}"><span class="nxSideCode">${code}</span><span class="nxSideIcon" aria-hidden="true">${icon}</span><strong>${title}</strong><small>${subtitle}</small></a>`;
  const buildHomeHub=()=>{
    if(document.querySelector('#bootHome .nxHomeHub'))return;
    const hero=document.querySelector('#bootHome .neonHomeHero'),menu=document.querySelector('#bootHome .neonHomeMenu'),quick=document.querySelector('#bootHome .neonHomeQuickRow');
    const single=document.getElementById('singleModeBtn'),bot=document.getElementById('botModeBtn'),online=document.getElementById('onlineModeBtn');
    if(!hero||!menu||!single||!bot||!online)return;
    const hub=document.createElement('div');hub.className='nxHomeHub';hub.innerHTML=`
      <section class="nxZone nxDraftZone" aria-labelledby="nxDraftTitle"><div class="nxZoneHead"><div><div class="nxEyebrow">Ana oyun</div><h2 id="nxDraftTitle">Draft</h2><p class="nxZoneCopy">Kadronu kur, taktiğini seç ve NEON XI maç motorunda üstünlüğünü kanıtla.</p></div><span class="nxZoneIndex">01</span></div><div class="nxDraftModes"></div><div class="nxDraftUtility"><span>Takım kurma • taktik • maç motoru</span></div></section>
      <section class="nxZone nxSideZone" aria-labelledby="nxSideTitle"><div class="nxZoneHead"><div><div class="nxEyebrow">Yan oyunlar</div><h2 id="nxSideTitle">Neon Arcade</h2><p class="nxZoneCopy">Kısa, rekabetçi ve futbol bilgisini sınayan farklı oyunlar.</p></div><span class="nxZoneIndex">02</span></div><div class="nxSideGrid">${card('./side-games/football-xox/index.html','3×3','×','Futbol XOX','Kesişimi bul • kareyi kap')}${card('./side-games/career-twin/index.html','02','⌁','Career Twin','Kariyer ikizini keşfet')}${card('./side-games/futbol-imposter.html','03','◈','Futbol Imposter','Aranızdaki sahteyi bul')}</div><a class="nxAllGames nxPressable" href="./side-games/index.html"><span>Tüm yan oyunları aç</span><b aria-hidden="true">→</b></a></section>`;
    const modes=hub.querySelector('.nxDraftModes');[single,bot,online].forEach(button=>{button.classList.add('nxPressable');modes.appendChild(button)});
    const tournament=quick?.querySelector('button');if(tournament){tournament.className='nxTournament nxPressable';tournament.innerHTML='TURNUVA MODU <span aria-hidden="true">↗</span>';hub.querySelector('.nxDraftUtility').appendChild(tournament)}
    hero.appendChild(hub);
  };
  const addPressFeedback=()=>{document.addEventListener('pointerdown',event=>{const target=event.target.closest('#bootHome .nxPressable');if(!target)return;target.classList.add('is-pressed');const rect=target.getBoundingClientRect(),pulse=document.createElement('span');pulse.className='nxPulse';pulse.style.left=`${event.clientX-rect.left}px`;pulse.style.top=`${event.clientY-rect.top}px`;target.appendChild(pulse);window.setTimeout(()=>pulse.remove(),650)});const release=()=>document.querySelectorAll('#bootHome .is-pressed').forEach(el=>el.classList.remove('is-pressed'));document.addEventListener('pointerup',release);document.addEventListener('pointercancel',release)};
  const init=()=>{addStyles();buildHomeHub();addPressFeedback()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();window.setTimeout(buildHomeHub,250);window.setTimeout(buildHomeHub,1000);
})();
