(()=>{
const MS=15000,EM=['⚽','🔥','🐐','👑','🇧🇷','🇦🇷','🇵🇹','🇹🇷','🚀','🧱','🧤','🎯','🪄','🦁','🐢','🤡','💀','❤️','😎','🧠','💪','🏆','⚡','🎩'];
let ht=null,ui=null,busy=false,lastVR=-1;
const O=()=>{let o=state.online;o.gamePhase??='idle';o.responses??=[];o.readyPlayers??=[];o.votes??={};o.voteCount??=0;o.voteRound??=0;o.turnIndex??=0;o.turnDeadline??=0;o.phaseRevision??=0;o.tiebreakNo??=0;o.result??=null;o.tieTally??=null;o.myVoteSubmitted??=false;o.myReadySent??=false;return o};
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const P=id=>O().players.find(x=>x.id===id),CP=()=>O().players[O().turnIndex];
const S=p=>p==='reveal'?'online-reveal':(['discussion','emoji','tiebreak'].includes(p)?'online-discussion':p==='voting'?'online-voting':p==='result'?'online-result':'online-lobby');
let st=document.createElement('style');st.textContent=`.og-timer{width:74px;height:74px;border:2px solid #39ff88;border-radius:50%;display:grid;place-items:center;margin:12px auto;font:900 24px Orbitron;color:#39ff88}.og-timer.bad{color:#ff4d62;border-color:#ff4d62}.og-turn{text-align:center;font:900 18px Orbitron;color:#fff}.og-turn b{color:#39ff88}.og-feed{display:flex;flex-direction:column;gap:7px;margin:12px 0}.og-row{display:grid;grid-template-columns:34% 1fr;gap:8px;padding:9px 11px;border:1px solid rgba(255,255,255,.08);border-radius:13px}.og-r{font:800 10px Orbitron;color:#6f9183;margin-top:8px}.og-name{font-weight:800;color:#a7cfbe}.og-emoji{font-size:24px}.og-grid{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.og-em{aspect-ratio:1;border-radius:12px;border:1px solid rgba(57,255,136,.2);background:#07100d;font-size:23px}.og-votes{display:grid;grid-template-columns:1fr 1fr;gap:9px}.og-vote{min-height:58px;border-radius:14px;border:1px solid rgba(57,255,136,.25);background:#07100d;color:white;font:800 15px Rajdhani}.og-led{margin:18px 0;padding:18px 10px;text-align:center;border:1px solid #ff304c;border-radius:16px;color:#ff304c;font:900 18px Orbitron;text-shadow:0 0 9px #ff304c,0 0 22px #ff304c}.og-result{text-align:center;font:900 34px Orbitron}.og-tie{text-align:center;border:1px solid #e9b849;border-radius:14px;padding:11px;color:#e9b849;margin:10px 0}@media(max-width:390px){.og-votes{grid-template-columns:1fr}}`;document.head.appendChild(st);
function tickStop(){if(ui){clearInterval(ui);ui=null}}function tick(){tickStop();ui=setInterval(()=>{let n=document.querySelector('[data-ogt]'),o=O();if(!n)return;let s=Math.ceil(Math.max(0,o.turnDeadline-Date.now())/1000);n.textContent=String(s).padStart(2,'0');n.classList.toggle('bad',s<=5)},200)}
function hstop(){if(ht){clearTimeout(ht);ht=null}}function hsched(){hstop();let o=O();if(!o.isHost||!['discussion','emoji','tiebreak'].includes(o.gamePhase))return;let r=o.phaseRevision,i=o.turnIndex;ht=setTimeout(()=>{let n=O();if(n.phaseRevision===r&&n.turnIndex===i&&CP())accept(CP().id,'',1)},Math.max(0,o.turnDeadline-Date.now())+40)}
function snap(){let o=O();return{code:o.code,hostId:o.hostId||o.myId,status:o.status,players:o.players,round:o.round,footballer:o.footballer,imposterId:o.imposterId,gamePhase:o.gamePhase,phaseRevision:o.phaseRevision,turnIndex:o.turnIndex,turnDeadline:o.turnDeadline,responses:o.responses,readyPlayers:o.readyPlayers,voteCount:o.voteCount,voteRound:o.voteRound,tiebreakNo:o.tiebreakNo,tieTally:o.tieTally,result:o.result}}
lobbySnapshot=snap;
applyLobbyState=d=>{if(!d)return;let o=O(),vr=o.voteRound;['code','hostId','status','footballer','imposterId','gamePhase','tieTally','result'].forEach(k=>{if(d[k]!==undefined)o[k]=d[k]});o.players=d.players||o.players;o.round=+d.round||0;o.phaseRevision=+d.phaseRevision||0;o.turnIndex=+d.turnIndex||0;o.turnDeadline=+d.turnDeadline||0;o.responses=d.responses||[];o.readyPlayers=d.readyPlayers||[];o.voteCount=+d.voteCount||0;o.voteRound=+d.voteRound||0;o.tiebreakNo=+d.tiebreakNo||0;if(vr!==o.voteRound){o.myVoteSubmitted=false;busy=false}if(o.status==='playing'){state.screen=S(o.gamePhase||'reveal');render()}else if(!['online-create','online-join'].includes(state.screen)){state.screen='online-lobby';render()}};
let oldBind=bindHostConnection;bindHostConnection=c=>{oldBind(c);c.on('data',m=>{if(m?.type==='game-action'&&c.__neonPlayerId)hostAction(c.__neonPlayerId,m.action||{})})};
function action(a){let o=O();if(o.isHost){hostAction(o.myId,a);return}if(p2pHostConnection?.open)sendConn(p2pHostConnection,{type:'game-action',action:a})}
function hostAction(id,a){let o=O();if(!o.isHost||!o.players.some(p=>p.id===id))return;if(a.type==='ready'&&o.gamePhase==='reveal'){if(!o.readyPlayers.includes(id))o.readyPlayers.push(id);broadcastLobbyState();render()}else if(a.type==='submit'&&['discussion','emoji','tiebreak'].includes(o.gamePhase)&&CP()?.id===id)accept(id,a.value,0);else if(a.type==='vote'&&o.gamePhase==='voting')vote(id,a.targetId)}
function reset(){let o=O();Object.assign(o,{responses:[],readyPlayers:[],votes:{},voteCount:0,voteRound:0,turnIndex:0,turnDeadline:0,tiebreakNo:0,tieTally:null,result:null,myVoteSubmitted:false,myReadySent:false});o.phaseRevision++;busy=false}
startOnlineRound=()=>{let o=O();if(!o.isHost||o.players.length<3)return;hstop();o.status='playing';o.footballer=pick(FOOTBALLERS);o.imposterId=pick(o.players).id;o.round=(+o.round||0)+1;reset();o.gamePhase='reveal';o.revealed=false;broadcastLobbyState();state.screen='online-reveal';render()};
function ready(){let o=O();if(o.myReadySent)return;o.myReadySent=true;if(o.isHost&&!o.readyPlayers.includes(o.myId))o.readyPlayers.push(o.myId);action({type:'ready'})}
function begin(ph){let o=O();o.gamePhase=ph;o.turnIndex=0;o.turnDeadline=Date.now()+MS;o.phaseRevision++;busy=false;broadcastLobbyState();state.screen='online-discussion';render();hsched()}
function roundKey(){let o=O();if(o.gamePhase==='emoji')return'emoji';if(o.gamePhase==='tiebreak')return'extra-'+o.tiebreakNo;return o.responses.some(r=>r.roundKey==='round-2')?'round-2':'round-1'}
function valid(v){v=String(v||'').trim().replace(/\s+/g,' ');let w=v?v.split(' ').length:0;return!v?null:(v.length<=40&&w<=5?v:null)}
function accept(id,v,to){let o=O(),p=CP();if(!o.isHost||!p||p.id!==id)return;hstop();let k=roundKey(),kind=o.gamePhase==='emoji'?'emoji':'text',txt='';if(to){txt='CEVAP VERMEDİ';kind='timeout'}else if(o.gamePhase==='emoji'){if(!EM.includes(String(v)))return;txt=String(v)}else{txt=valid(v);if(!txt)return}o.responses.push({roundKey:k,playerId:p.id,name:p.name,text:txt,kind});advance()}
function advance(){let o=O();if(o.turnIndex<o.players.length-1){o.turnIndex++;o.turnDeadline=Date.now()+MS;o.phaseRevision++;busy=false;broadcastLobbyState();render();hsched();return}if(o.gamePhase==='discussion'){if(!o.responses.some(r=>r.roundKey==='round-2')){o.turnIndex=0;o.turnDeadline=Date.now()+MS;o.phaseRevision++;busy=false;broadcastLobbyState();render();hsched()}else begin('emoji')}else beginVote()}
function beginVote(){let o=O();hstop();Object.assign(o,{gamePhase:'voting',votes:{},voteCount:0,turnDeadline:0,myVoteSubmitted:false});o.voteRound++;o.phaseRevision++;busy=false;broadcastLobbyState();state.screen='online-voting';render()}
function vote(id,t){let o=O();if(!o.isHost||id===t||o.votes[id]||!o.players.some(p=>p.id===id)||!o.players.some(p=>p.id===t))return;o.votes[id]=t;o.voteCount=Object.keys(o.votes).length;if(id===o.myId)o.myVoteSubmitted=true;if(o.voteCount===o.players.length)finishVote();else{broadcastLobbyState();render()}}
function finishVote(){let o=O(),t={};o.players.forEach(p=>t[p.id]=0);Object.values(o.votes).forEach(id=>t[id]++);let m=Math.max(...Object.values(t)),top=Object.keys(t).filter(id=>t[id]===m);if(top.length!==1){o.tieTally=t;o.tiebreakNo++;o.votes={};o.voteCount=0;begin('tiebreak');return}o.result={imposterWon:top[0]!==o.imposterId,accusedId:top[0],imposterId:o.imposterId,tally:t};o.gamePhase='result';o.phaseRevision++;broadcastLobbyState();state.screen='online-result';render()}
renderOnlineReveal=app=>{let o=O(),imp=o.imposterId===o.myId;header(app,'OYUN '+o.round,o.myName.toUpperCase(),'Rolünü kimse görmesin');let hb=el('button','btn ghost','GİZLE'),peel=buildPeelCard(o.revealed,imp,o.footballer,r=>{o.revealed=r;hb.classList.toggle('hidden',!r);if(r)ready()});app.appendChild(peel);app.appendChild(el('div','peel-caption','Kartın sağ alt köşesini yukarı doğru kaydır'));hb.classList.toggle('hidden',!o.revealed);hb.onclick=()=>{o.revealed=false;render()};app.appendChild(hb);app.appendChild(el('div','card center-txt','<div class="section-title">HAZIR</div><div class="info-text">'+o.readyPlayers.length+' / '+o.players.length+' oyuncu rolünü gördü</div>'));if(o.isHost){let b=el('button','btn solid','TARTIŞMAYI BAŞLAT');b.disabled=o.readyPlayers.length<o.players.length;b.onclick=()=>begin('discussion');app.appendChild(b)}else app.appendChild(el('div','info-text','Lobi sahibinin tartışmayı başlatması bekleniyor.'))};
function label(k){return k==='round-1'?'TUR 1':k==='round-2'?'TUR 2':k==='emoji'?'TUR 3 · EMOJİ':'EK TUR '+k.split('-')[1]}
function feed(app){let o=O(),f=el('div','og-feed'),last='';o.responses.forEach(r=>{if(r.roundKey!==last){f.appendChild(el('div','og-r',label(r.roundKey)));last=r.roundKey}f.appendChild(el('div','og-row','<div class="og-name">'+E(r.name)+'</div><div class="'+(r.kind==='emoji'?'og-emoji':'')+'">'+E(r.text)+'</div>'))});if(o.responses.length)app.appendChild(f)}
function rt(){let o=O();if(o.gamePhase==='emoji')return['TUR 3 / 3','SADECE 1 EMOJİ'];if(o.gamePhase==='tiebreak')return['EK TUR '+o.tiebreakNo,'OYLAR EŞİT'];return o.responses.some(r=>r.roundKey==='round-2')?['TUR 2 / 3','BİR İPUCU DAHA']:['TUR 1 / 3','KENDİNİ AKLA']}
renderOnlineDiscussion=app=>{let o=O(),p=CP(),[a,b]=rt();header(app,a,b,o.gamePhase==='emoji'?'Sadece bir emoji seç':'15 saniyede birkaç kelime yaz');if(o.gamePhase==='tiebreak')app.appendChild(el('div','og-tie','OYlar eşit · Bir kısa açıklama turu daha'));app.appendChild(el('div','card','<div class="og-turn">SIRA: <b>'+E(p?.name||'—')+'</b></div><div class="og-timer" data-ogt>15</div>'));feed(app);if(p?.id===o.myId){if(o.gamePhase==='emoji'){let g=el('div','card'),gr=el('div','og-grid');EM.forEach(x=>{let z=el('button','og-em',x);z.disabled=busy;z.onclick=()=>{busy=true;gr.querySelectorAll('button').forEach(q=>q.disabled=true);action({type:'submit',value:x})};gr.appendChild(z)});g.appendChild(gr);app.appendChild(g)}else{let c=el('div','card'),i=el('input');i.maxLength=40;i.placeholder='En fazla 5 kelime';let er=el('div','error-text',''),b=el('button','btn solid','GÖNDER');b.onclick=()=>{let v=valid(i.value);if(!v){er.textContent='En fazla 5 kelime / 40 karakter.';return}busy=true;i.disabled=b.disabled=true;action({type:'submit',value:v})};c.appendChild(i);c.appendChild(er);c.appendChild(b);app.appendChild(c)}}else app.appendChild(el('div','card center-txt','<div class="info-text">'+E(p?.name||'Oyuncu')+' yazıyor…</div>'));tick();if(o.isHost)hsched()};
renderOnlineVoting=app=>{tickStop();hstop();let o=O();if(lastVR!==o.voteRound){lastVR=o.voteRound;busy=false}header(app,'OY VER','İMPOSTER KİM?','Oylar sonuç açıklanana kadar gizli');feed(app);app.appendChild(el('div','card center-txt','<div class="section-title">'+o.voteCount+' / '+o.players.length+' OY</div>'));if(!o.myVoteSubmitted){let g=el('div','og-votes');o.players.filter(p=>p.id!==o.myId).forEach(p=>{let b=el('button','og-vote',E(p.name));b.onclick=()=>{if(busy)return;busy=true;o.myVoteSubmitted=true;g.querySelectorAll('button').forEach(x=>x.disabled=true);action({type:'vote',targetId:p.id});render()};g.appendChild(b)});app.appendChild(g)}else app.appendChild(el('div','card center-txt','<div class="info-text">Oyun kaydedildi. Diğer oyuncular bekleniyor…</div>'))};
renderOnlineResult=app=>{let o=O(),r=o.result||{},im=P(r.imposterId||o.imposterId);header(app,'OYUN BİTTİ','SONUÇ','İmposter artık gizli değil');app.appendChild(el('div','og-result',r.imposterWon?'IMPOSTER KAZANDI':'IMPOSTER KAYBETTİ'));app.appendChild(el('div','og-led','IMPOSTER '+E(im?.name?.toUpperCase()||'?')+' İDİ'));let t=r.tally||{},c=el('div','card');[...o.players].sort((a,b)=>(t[b.id]||0)-(t[a.id]||0)).forEach(p=>c.appendChild(el('div','og-row','<div class="og-name">'+E(p.name)+(p.id===r.imposterId?' · IMPOSTER':'')+'</div><div>'+String(t[p.id]||0)+' OY</div>')));app.appendChild(c);if(o.isHost){let b=el('button','btn solid','AYNI LOBİYLE YENİ OYUN');b.onclick=startOnlineRound;app.appendChild(b)}};
let oldLeave=leaveLobby;leaveLobby=()=>{tickStop();hstop();busy=false;lastVR=-1;return oldLeave()};
render=()=>{tickStop();let a=document.getElementById('app');a.innerHTML='';let w=el('div','screen'),m={menu:renderMenu,'local-setup':renderLocalSetup,'local-reveal':renderLocalReveal,'local-done':renderLocalDone,'online-choice':renderOnlineChoice,'online-create':renderOnlineCreate,'online-join':renderOnlineJoin,'online-lobby':renderOnlineLobby,'online-reveal':renderOnlineReveal,'online-discussion':renderOnlineDiscussion,'online-voting':renderOnlineVoting,'online-result':renderOnlineResult};(m[state.screen]||renderMenu)(w);a.appendChild(w)};
O();
})();