'use strict';
(() => {
  const PREFIX='neonxi-career-twin-';
  const METRICS=[
    ['height_cm','BOY'],['weight_kg','KİLO'],['birth_date','DOĞUM TARİHİ'],['club_count','KULÜP SAYISI'],['trophies','KUPA SAYISI'],['career_goals','KARİYER GOLÜ'],['career_assists','KARİYER ASİSTİ'],['peak_market_value_eur','EN YÜKSEK PİYASA DEĞERİ'],['career_appearances','KARİYER MAÇI']
  ].map(([key,label])=>({key,label}));
  const app=document.getElementById('app');
  let PLAYERS=[],BY_ID=new Map(),peer=null,hostConn=null,guestConn=null,hostGame=null,remote=null,timer=null;
  const S={screen:'boot',role:null,name:'',code:'',error:'',pending:false,search:''};
  const esc=s=>String(s??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const E=(tag,cls,html)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(html!==undefined)e.innerHTML=html;return e};
  const btn=(txt,primary,fn)=>{const b=E('button','btn'+(primary?' primary':''),esc(txt));b.type='button';b.onclick=fn;return b};
  function top(){const t=E('div','topbar');const a=E('a','back','← YAN OYUNLAR');a.href='../index.html';t.append(a,E('div','pool',PLAYERS.length?PLAYERS.length+' OYUNCU':''));app.appendChild(t)}
  function brand(sub){const b=E('div','brand');b.innerHTML='<div class="eyebrow">NEON XI · SIDE GAME</div><h1>KARİYER <span>İKİZİ</span></h1><div class="subtitle">'+esc(sub||'Hedef futbolcuya en yakın kariyeri seç')+'</div>';app.appendChild(b)}
  function field(label,placeholder,value,max){const w=E('div');w.appendChild(E('div','label',esc(label)));const i=E('input','field');i.placeholder=placeholder;i.value=value||'';if(max)i.maxLength=max;w.appendChild(i);return [w,i]}
  function resetView(){app.innerHTML=''}
  function render(){resetView();top();if(S.screen==='boot')return renderBoot();if(S.screen==='menu')return renderMenu();if(S.screen==='create')return renderCreate();if(S.screen==='join')return renderJoin();if(S.screen==='lobby')return renderLobby();if(S.screen==='game')return renderGame()}
  function renderBoot(){brand('Oyuncu havuzu yükleniyor…');const c=E('div','card center','<div class="spinner"></div><div class="hint">Veriler hazırlanıyor.</div>');app.appendChild(c)}
  function renderMenu(){brand();const c=E('div','card');c.append(E('div','label','2 OYUNCULU ONLINE OYUN'),btn('ODA KUR',true,()=>{S.screen='create';S.error='';render()}),btn('KODLA KATIL',false,()=>{S.screen='join';S.error='';render()}));app.appendChild(c);const i=E('div','card','<div class="label">NASIL OYNANIR?</div><div class="hint">Aynı hedef futbolcu 9 tur boyunca ortada kalır. Her tur bir kariyer parametresi açılır. Hedef değere daha yakın futbolcuyu seçen oyuncu puanı alır. Seçimler, iki taraf da kilitleyene kadar rakibe görünmez.</div>');app.appendChild(i)}
  function renderCreate(){brand('4 haneli oda oluştur');const c=E('div','card');const [w,n]=field('ADIN','Adın',S.name,24);c.append(w,btn('ODAYI KUR',true,()=>createRoom(n.value.trim())),E('div','error',esc(S.error)));app.appendChild(c)}
  function renderJoin(){brand('Oda koduyla katıl');const c=E('div','card');const [cw,ci]=field('ODA KODU','1234',S.code,4);ci.inputMode='numeric';ci.oninput=()=>ci.value=ci.value.replace(/\D/g,'').slice(0,4);const [nw,ni]=field('ADIN','Adın',S.name,24);c.append(cw,nw,btn('KATIL',true,()=>joinRoom(ci.value,ni.value.trim())),E('div','error',esc(S.error)));app.appendChild(c)}
  function renderLobby(){brand(S.role==='host'?'İkinci oyuncu bekleniyor':'Odaya bağlanılıyor');const c=E('div','card center');c.innerHTML='<div class="label">ODA KODU</div><div class="code">'+esc(S.code)+'</div><div class="spinner"></div><div class="hint">'+(S.role==='host'?'Kodu arkadaşınla paylaş. İkinci oyuncu girince oyun otomatik başlar.':'Bağlantı kuruluyor…')+'</div><div class="error">'+esc(S.error)+'</div>';app.appendChild(c)}
  async function loadPeer(){if(window.Peer)return;await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://unpkg.com/peerjs@1.5.5/dist/peerjs.min.js';s.onload=res;s.onerror=()=>rej(new Error('peerjs'));document.head.appendChild(s)})}
  function cleanup(){clearTimeout(timer);try{hostConn&&hostConn.close()}catch{}try{guestConn&&guestConn.close()}catch{}try{peer&&peer.destroy()}catch{}peer=hostConn=guestConn=null;hostGame=remote=null;S.pending=false}
  function code(){return String(Math.floor(1000+Math.random()*9000))}
  async function createRoom(name){if(!name){S.error='Adını yaz.';render();return}cleanup();S.name=name;S.role='host';S.screen='lobby';S.error='';render();try{await loadPeer();await makeHost(0)}catch{S.error='Oda oluşturulamadı. Tekrar dene.';render()}}
  function makeHost(attempt){return new Promise((resolve,reject)=>{if(attempt>7)return reject(new Error('codes'));const c=code();S.code=c;const p=new Peer(PREFIX+c,{debug:0});peer=p;let opened=false;p.on('open',()=>{opened=true;p.on('connection',acceptGuest);render();resolve()});p.on('error',err=>{if(!opened&&(err.type==='unavailable-id'||err.type==='invalid-id')){try{p.destroy()}catch{}makeHost(attempt+1).then(resolve,reject)}else if(!opened)reject(err)})})}
  function acceptGuest(c){if(hostConn&&hostConn.open){c.on('open',()=>c.send({type:'reject',message:'Oda dolu.'}));return}hostConn=c;let joined=false;c.on('data',m=>{if(!m||typeof m!=='object')return;if(m.type==='join'&&!joined){const name=String(m.name||'').trim().slice(0,24);if(!name)return c.send({type:'reject',message:'Geçersiz isim.'});joined=true;c.send({type:'accepted'});startGame(name);return}if(!joined||!hostGame)return;if(m.type==='pick')hostPick('guest',Number(m.id),Number(m.round))});c.on('close',()=>{if(joined){S.error='Rakibin bağlantısı koptu.';S.screen='lobby';hostGame=null;render()}})}
  async function joinRoom(c,name){if(!/^\d{4}$/.test(c)){S.error='4 haneli kod gir.';render();return}if(!name){S.error='Adını yaz.';render();return}cleanup();S.code=c;S.name=name;S.role='guest';S.screen='lobby';S.error='';render();try{await loadPeer();peer=new Peer(undefined,{debug:0});peer.on('open',()=>{guestConn=peer.connect(PREFIX+c,{reliable:true});guestConn.on('open',()=>guestConn.send({type:'join',name}));guestConn.on('data',m=>{if(!m||typeof m!=='object')return;if(m.type==='reject'){S.error=m.message||'Katılım reddedildi.';render()}if(m.type==='state'){remote=m;S.pending=false;S.screen='game';render()}});guestConn.on('close',()=>{S.error='Oda sahibi bağlantıyı kapattı.';S.screen='lobby';render()})});peer.on('error',()=>{})}catch{S.error='Bağlantı servisi yüklenemedi.';render()}}
  function targetPlayer(){const ordered=PLAYERS.slice().sort((a,b)=>(b.recognition_score||0)-(a.recognition_score||0));const pool=ordered.slice(0,Math.min(500,ordered.length));return pool[Math.floor(Math.random()*Math.min(pool.length,220))]||pool[0]}
  function startGame(guest){clearTimeout(timer);const t=targetPlayer();hostGame={players:{host:S.name,guest},targetId:Number(t.id),round:0,phase:'pick',scores:{host:0,guest:0},picks:{host:null,guest:null},used:{host:[],guest:[]},result:null,rev:1};S.screen='game';S.search='';broadcast();render()}
  function snap(role){const g=hostGame,opp=role==='host'?'guest':'host',show=g.phase==='reveal'||g.phase==='final';return{type:'state',role,players:g.players,targetId:g.targetId,round:g.round,phase:g.phase,scores:g.scores,ownPick:g.picks[role],oppPicked:!!g.picks[opp],picks:show?g.picks:null,used:g.used[role],result:show?g.result:null,rev:g.rev}}
  function view(){return S.role==='host'&&hostGame?snap('host'):remote}
  function broadcast(){if(hostGame&&hostConn&&hostConn.open)hostConn.send(snap('guest'))}
  function metricNum(p,key){if(key==='birth_date')return Date.parse(p[key])/86400000;return Number(p[key])}
  function format(v,key){if(key==='birth_date'){const d=new Date(v);return String(d.getUTCDate()).padStart(2,'0')+'.'+String(d.getUTCMonth()+1).padStart(2,'0')+'.'+d.getUTCFullYear()}if(key==='height_cm')return v+' cm';if(key==='weight_kg')return v+' kg';if(key==='club_count')return v+' kulüp';if(key==='trophies')return v+' kupa';if(key==='career_goals')return v+' gol';if(key==='career_assists')return v+' asist';if(key==='career_appearances')return v+' maç';if(key==='peak_market_value_eur')return '€'+(Number(v)/1000000).toLocaleString('tr-TR',{maximumFractionDigits:1})+' M';return String(v)}
  function hostPick(role,id,round){const g=hostGame;if(!g||g.phase!=='pick'||round!==g.round||g.picks[role])return;const p=BY_ID.get(id);if(!p||id===g.targetId||g.used[role].includes(id))return;g.picks[role]=id;g.rev++;if(g.picks.host&&g.picks.guest)resolve();broadcast();render()}
  function resolve(){const g=hostGame,m=METRICS[g.round],t=BY_ID.get(g.targetId),a=BY_ID.get(g.picks.host),b=BY_ID.get(g.picks.guest);const tv=metricNum(t,m.key),av=metricNum(a,m.key),bv=metricNum(b,m.key),da=Math.abs(av-tv),db=Math.abs(bv-tv);let winner='draw';if(da<db)winner='host';else if(db<da)winner='guest';if(winner!=='draw')g.scores[winner]++;g.used.host.push(a.id);g.used.guest.push(b.id);g.result={winner,hostValue:a[m.key],guestValue:b[m.key],targetValue:t[m.key],hostDiff:da,guestDiff:db};g.phase='reveal';g.rev++;const rev=g.rev;timer=setTimeout(()=>{if(!hostGame||hostGame.rev!==rev)return;if(g.round===8){g.phase='final';g.rev++;broadcast();render()}else{g.round++;g.phase='pick';g.picks={host:null,guest:null};g.result=null;g.rev++;S.search='';broadcast();render()}},4200)}
  function choose(id){const v=view();if(!v||v.phase!=='pick'||v.ownPick||S.pending)return;if(S.role==='host')hostPick('host',id,v.round);else if(guestConn&&guestConn.open){S.pending=true;guestConn.send({type:'pick',id,round:v.round});render()}}
  function progress(v){const p=E('div','progress');for(let i=0;i<9;i++)p.appendChild(E('div','pip'+(i<v.round?' done':i===v.round?' now':'')));app.appendChild(p)}
  function renderGame(){const v=view();if(!v){brand('Oyun durumu bekleniyor…');app.appendChild(E('div','card center','<div class="spinner"></div>'));return}if(v.phase==='final')return renderFinal(v);brand('Hedef futbolcuya en çok yaklaş');const m=METRICS[v.round],t=BY_ID.get(Number(v.targetId));if(!t){app.appendChild(E('div','card error','Hedef oyuncu verisi bulunamadı.'));return}app.appendChild(E('div','scorebar','<div class="score"><div class="n">'+esc(v.players.host)+'</div><div class="p">'+v.scores.host+'</div></div><div class="roundBadge">'+(v.round+1)+' / 9</div><div class="score right"><div class="n">'+esc(v.players.guest)+'</div><div class="p">'+v.scores.guest+'</div></div>'));app.appendChild(E('div','metricTitle','<span>PARAMETRE</span><b>'+esc(m.label)+'</b>'));progress(v);renderArena(v,t,m);if(v.phase==='pick')renderPicker(v,t);else renderReveal(v)}
  function renderArena(v,t,m){const box=E('div','arena');for(const role of ['host','target','guest']){const target=role==='target';const s=E('div','slot'+(target?' target':''));s.appendChild(E('div','who',esc(target?'HEDEF':v.players[role])));if(target){s.appendChild(E('div','name',esc(t.name)));if(v.phase==='reveal')s.appendChild(E('div','val',esc(format(t[m.key],m.key))))}else{let p=null;if(v.phase==='reveal'&&v.picks)p=BY_ID.get(Number(v.picks[role]));else if(role===v.role&&v.ownPick)p=BY_ID.get(Number(v.ownPick));if(p){s.appendChild(E('div','name',esc(p.name)));if(v.phase==='reveal'){const r=v.result,val=role==='host'?r.hostValue:r.guestValue;s.appendChild(E('div','val',esc(format(val,m.key))));if(r.winner===role)s.classList.add('win');if(r.winner==='draw')s.classList.add('draw')}else s.appendChild(E('div','lock','KİLİTLENDİ'))}else{s.appendChild(E('div','name',(role===v.role?v.ownPick:v.oppPicked)?'SEÇİM YAPILDI':'BEKLİYOR'))}}box.appendChild(s)}app.appendChild(box)}
  function norm(s){return String(s||'').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
  function renderPicker(v,t){if(v.ownPick||S.pending){app.appendChild(E('div','statusBox',S.pending?'Seçimin gönderiliyor…':'Seçimin kilitlendi. Rakibin bekleniyor.'));return}const c=E('div','card searchBox');c.appendChild(E('div','searchHead','<b>FUTBOLCUNU SEÇ</b><span>dokununca kilitlenir</span>'));const i=E('input','field');i.placeholder='Oyuncu ara…';i.value=S.search;const list=E('div','results');const fill=()=>{S.search=i.value;list.innerHTML='';const q=norm(S.search),used=new Set(v.used||[]);const arr=PLAYERS.filter(p=>Number(p.id)!==Number(t.id)&&!used.has(Number(p.id))&&(!q||norm(p.name).includes(q))).sort((a,b)=>(b.recognition_score||0)-(a.recognition_score||0)).slice(0,18);for(const p of arr){const b=E('button','playerBtn','<span><b>'+esc(p.name)+'</b><small>'+esc([p.club,p.country].filter(Boolean).join(' · '))+'</small></span><span class="arrow">›</span>');b.type='button';b.onclick=()=>choose(Number(p.id));list.appendChild(b)}if(!arr.length)list.appendChild(E('div','statusBox','Oyuncu bulunamadı.'))};i.oninput=fill;c.append(i,list);fill();app.appendChild(c)}
  function renderReveal(v){const r=v.result;if(!r)return;const text=r.winner==='draw'?'BERABERE':(r.winner==='host'?v.players.host:v.players.guest)+' BU TURU KAZANDI';app.append(E('div','revealTitle','İKİ SEÇİM DE AÇILDI'),E('div','winnerText'+(r.winner==='draw'?' draw':''),esc(text)),E('div','statusBox','Sonraki parametre otomatik açılacak.'))}
  function renderFinal(v){brand('9 parametre tamamlandı');const c=E('div','card');const hs=v.scores.host,gs=v.scores.guest,t=BY_ID.get(Number(v.targetId));const title=hs===gs?'OYUN BERABERE':hs>gs?v.players.host+' KAZANDI':v.players.guest+' KAZANDI';c.append(E('div','label center','FİNAL'),E('div','finalTitle',esc(title.toUpperCase())),E('div','finalScore',hs+' — '+gs),E('div','center hint','Hedef futbolcu: <b>'+esc(t?.name||'—')+'</b>'));app.appendChild(c);if(S.role==='host')app.appendChild(btn('AYNI ODAYLA YENİ OYUN',true,()=>startGame(hostGame.players.guest)));app.appendChild(btn('YAN OYUNLARA DÖN',false,()=>{cleanup();location.href='../index.html'}))}
  async function init(){render();try{const r=await fetch('./data/players.json',{cache:'no-store'});if(!r.ok)throw new Error('http '+r.status);const raw=await r.json();PLAYERS=raw.filter(p=>p&&p.playable!==false&&METRICS.every(m=>p[m.key]!==null&&p[m.key]!==undefined&&p[m.key]!==''));BY_ID=new Map(PLAYERS.map(p=>[Number(p.id),p]));if(!PLAYERS.length)throw new Error('empty');S.screen='menu';render()}catch(err){console.error(err);resetView();top();brand('Oyuncu verisi yüklenemedi');app.appendChild(E('div','card error','Veri dosyası açılamadı. Sayfayı yenileyip tekrar dene.'))}}
  window.addEventListener('beforeunload',cleanup);
  init();
})();