'use strict';
(() => {
  const PREFIX='neonxi-career-twin-';
  const METRICS=[
    ['height_cm','BOY'],['weight_kg','KİLO'],['birth_date','DOĞUM TARİHİ'],['club_count','KULÜP SAYISI'],['trophies','KUPA SAYISI'],['career_goals','KAYITLI GOL SAYISI'],['career_assists','KAYITLI ASİST SAYISI'],['peak_market_value_eur','EN YÜKSEK PİYASA DEĞERİ'],['career_appearances','KAYITLI MAÇ SAYISI']
  ].map(([key,label])=>({key,label}));
  const app=document.getElementById('app');
  let PLAYERS=[],SEARCH_PLAYERS=[],TARGET_PLAYERS=[],GAME_METRICS=[],BY_ID=new Map(),peer=null,hostConn=null,guestConn=null,hostGame=null,remote=null,localTurn='host';
  let chatLog=[],auxQueue=[],pendingTimer=null;
  const S={screen:'boot',role:null,name:'',code:'',error:'',pending:false,search:'',localPass:false,chatDraft:''};
  const esc=s=>String(s??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[ch]));
  const E=(tag,cls,html)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(html!==undefined)e.innerHTML=html;return e};
  const btn=(txt,primary,fn)=>{const b=E('button','btn'+(primary?' primary':''),esc(txt));b.type='button';b.onclick=fn;return b};
  function injectCss(){}
  function top(){const t=E('div','topbar');const a=E('a','back','YAN OYUNLAR');a.href='../index.html';a.setAttribute('aria-label','Yan oyunlara dön');t.append(a,E('div','pool',''));app.appendChild(t)}
  function brand(sub){const b=E('div','brand');b.innerHTML='<div class="eyebrow">NEON XI · SIDE GAME</div><h1>KARİYER <span>İKİZİ</span></h1><div class="subtitle">'+esc(sub||'Hedef futbolcuya en yakın kariyeri seç')+'</div>';app.appendChild(b)}
  function field(label,placeholder,value,max){const w=E('div');w.appendChild(E('div','label',esc(label)));const i=E('input','field');i.placeholder=placeholder;i.value=value||'';if(max)i.maxLength=max;w.appendChild(i);return[w,i]}
  function render(){const params=new URLSearchParams(location.search);window.scrollTo(0,0);document.body.dataset.ctScreen=S.screen;document.body.dataset.ctRole=S.role||'';document.body.dataset.ctCapture=params.get('capture')||'';document.body.dataset.ctQa=params.get('qa')||'';app.innerHTML='';top();if(S.screen==='boot')return renderBoot();if(S.screen==='menu')return renderMenu();if(S.screen==='create')return renderCreate();if(S.screen==='join')return renderJoin();if(S.screen==='lobby')return renderLobby();if(S.screen==='game')return renderGame()}
  function renderBoot(){brand('Oyuncu verileri yükleniyor…');app.appendChild(E('div','card center','<div class="spinner"></div><div class="hint">Transfermarkt master havuzu hazırlanıyor.</div>'))}
  function renderMenu(){brand();const c=E('div','card');c.append(E('div','label','OYUN MODU'));const g=E('div','modeGrid');g.append(btn('TEK TELEFON',true,startLocal),btn('ONLINE · ODA KUR',false,()=>{S.screen='create';S.error='';render()}),btn('ONLINE · KODLA KATIL',false,()=>{S.screen='join';S.error='';render()}));c.appendChild(g);app.appendChild(c);app.appendChild(E('div','card','<div class="label">NASIL OYNANIR?</div><div class="hint">Aynı hedef futbolcu '+GAME_METRICS.length+' tur boyunca ortada kalır. Her tur, Transfermarkt master havuzunda verisi bulunan bir parametre için hedefe en yakın futbolcuyu seçersiniz. Tek telefonda ilk seçim gizlenir ve telefon ikinci oyuncuya verilir.</div>'))}
  function renderCreate(){brand('4 haneli oda oluştur');const c=E('div','card');const[w,n]=field('ADIN','Adın',S.name,24);c.append(w,btn('ODAYI KUR',true,()=>createRoom(n.value.trim())),E('div','error',esc(S.error)));app.appendChild(c)}
  function renderJoin(){brand('Arkadaşının oda kodunu gir');const c=E('div','card');const[cw,ci]=field('ODA KODU','1234',S.code,4),[nw,ni]=field('ADIN','Adın',S.name,24);ci.inputMode='numeric';ci.oninput=()=>{ci.value=ci.value.replace(/\D/g,'').slice(0,4);S.code=ci.value};c.append(cw,nw,btn('KATIL',true,()=>joinRoom(ci.value.trim(),ni.value.trim())),E('div','error',esc(S.error)));app.appendChild(c)}
  function renderLobby(){brand(S.role==='host'?'Oda hazır · ikinci oyuncu bekleniyor':'Odaya bağlanılıyor…');const c=E('div','card center');c.append(E('div','label','ODA KODU'),E('div','code',esc(S.code)),E('div','spinner'),E('div','hint',S.role==='host'?'Bu kodu arkadaşınla paylaş. İkinci oyuncu girince oyun otomatik başlar.':'Oda sahibine bağlanılıyor…'));app.appendChild(c);if(S.error)app.appendChild(E('div','error',esc(S.error)))}
  async function loadPeer(){if(window.Peer)return;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://unpkg.com/peerjs@1.5.5/dist/peerjs.min.js';s.onload=resolve;s.onerror=()=>reject(new Error('PeerJS'));document.head.appendChild(s)})}
  function cleanup(){clearTimeout(pendingTimer);pendingTimer=null;try{hostConn&&hostConn.close()}catch{}try{guestConn&&guestConn.close()}catch{}try{peer&&peer.destroy()}catch{}peer=hostConn=guestConn=null;hostGame=remote=null;S.pending=false;S.localPass=false;auxQueue=[];chatLog=[]}
  const roomCode=()=>String(Math.floor(1000+Math.random()*9000));
  async function createRoom(name){if(!name){S.error='Önce adını yaz.';render();return}cleanup();S.name=name;S.role='host';S.screen='lobby';S.error='';render();try{await loadPeer();await tryHost(0)}catch{S.error='Oda kurulamadı. Tekrar dene.';render()}}
  function tryHost(attempt){return new Promise((resolve,reject)=>{if(attempt>=8)return reject(new Error('room'));const code=roomCode();S.code=code;const p=new Peer(PREFIX+code,{debug:0});peer=p;let opened=false;p.on('open',()=>{opened=true;p.on('connection',c=>{if(hostConn&&hostConn.open){c.on('open',()=>c.send({type:'reject',message:'Oda dolu.'}));return}hostConn=c;bindHostConnection(c)});render();resolve()});p.on('error',e=>{if(!opened&&(e.type==='unavailable-id'||e.type==='invalid-id')){try{p.destroy()}catch{}tryHost(attempt+1).then(resolve,reject)}else if(!opened)reject(e)})})}
  function bindHostConnection(c){let joined=false;c.on('open',flushAux);c.on('data',m=>{if(!m||typeof m!=='object')return;if(m.type==='join'&&!joined){const name=String(m.name||'').trim().slice(0,24);if(!name){c.send({type:'reject',message:'Geçersiz isim.'});return}joined=true;c.send({type:'accepted'});startGame(name);return}if(!joined)return;if(m.type==='chat'||m.type==='emoji'){receiveAux('guest',m);return}if(!joined)return;if(!hostGame)return;if(m.type==='select')hostSelect('guest',Number(m.playerId),Number(m.round));if(m.type==='next')advanceRound(Number(m.round));if(m.type==='rematch'&&hostGame.phase==='final')startGame(hostGame.players.guest)});c.on('close',()=>{if(joined){S.screen='lobby';S.error='Diğer oyuncunun bağlantısı koptu.';hostGame=null;render()}})}
  async function joinRoom(code,name){if(!/^\d{4}$/.test(code)){S.error='4 haneli oda kodu gir.';render();return}if(!name){S.error='Önce adını yaz.';render();return}cleanup();S.code=code;S.name=name;S.role='guest';S.screen='lobby';S.error='';render();try{await loadPeer();peer=new Peer(undefined,{debug:0});peer.on('open',()=>{guestConn=peer.connect(PREFIX+code,{reliable:true});bindGuestConnection(guestConn,name)});peer.on('error',()=>{if(S.screen==='lobby'){S.error='Bağlantı kurulamadı.';render()}});setTimeout(()=>{if(S.screen==='lobby'&&!remote){S.error='Oda bulunamadı veya bağlantı kurulamadı.';render()}},8000)}catch{S.error='Bağlantı servisi yüklenemedi.';render()}}
  function bindGuestConnection(c,name){c.on('open',()=>{c.send({type:'join',name});flushAux()});c.on('data',m=>{if(!m||typeof m!=='object')return;if(m.type==='reject'){S.error=m.message||'Odaya katılamadın.';render();return}if(m.type==='chat'||m.type==='emoji'){receiveAux('host',m);return}if(m.type==='state'){remote=m;S.screen='game';S.pending=false;clearTimeout(pendingTimer);pendingTimer=null;render()}});c.on('close',()=>{S.screen='lobby';S.error='Oda sahibi bağlantıyı kapattı.';remote=null;render()})}
  function chooseTarget(){const qaTarget=new URLSearchParams(location.search).get('qa')==='career-twin'&&TARGET_PLAYERS.find(p=>p.name==='Viktor Gyökeres');if(qaTarget)return qaTarget;const active=TARGET_PLAYERS.filter(p=>p.status==='active');const source=(active.length>120&&Math.random()<.85?active:TARGET_PLAYERS).slice().sort((a,b)=>(b.recognition_score||0)-(a.recognition_score||0));const cap=source.slice(0,Math.min(600,source.length));const weights=cap.map((p,i)=>Math.max(1,Math.sqrt(Math.max(1,p.recognition_score||1))*(1-i/(cap.length*1.4))));let r=Math.random()*weights.reduce((a,b)=>a+b,0);for(let i=0;i<cap.length;i++){r-=weights[i];if(r<=0)return cap[i]}return cap[0]}
  function startGame(guestName){const target=chooseTarget();if(!target)return;hostGame={players:{host:S.role==='local'?'Oyuncu 1':S.name,guest:guestName||'Oyuncu 2'},phase:'pick',round:0,targetId:target.id,metricKeys:GAME_METRICS.map(m=>m.key),scores:{host:0,guest:0},picks:{host:null,guest:null},used:{host:[],guest:[]},roundResult:null,revision:1};localTurn='host';S.localPass=false;S.screen='game';S.search='';S.pending=false;chatLog=[];broadcast();render()}
  function startLocal(){cleanup();S.role='local';startGame('Oyuncu 2')}
  function publicState(role){const g=hostGame,opp=role==='host'?'guest':'host',reveal=g.phase==='reveal'||g.phase==='final';return{type:'state',role,players:g.players,phase:g.phase,round:g.round,targetId:g.targetId,metricKeys:g.metricKeys,scores:g.scores,ownPick:g.picks[role],oppPicked:!!g.picks[opp],picks:reveal?g.picks:null,used:g.used[role],roundResult:reveal?g.roundResult:null,revision:g.revision}}
  function broadcast(){if(hostGame&&hostConn&&hostConn.open)hostConn.send(publicState('guest'))}
  function view(){if(S.role==='local'&&hostGame)return publicState(hostGame.phase==='pick'?localTurn:'host');return S.role==='host'&&hostGame?publicState('host'):remote}
  function numeric(p,key){if(!p)return NaN;if(key==='birth_date'){const d=Date.parse(p[key]);return Number.isFinite(d)?d/86400000:NaN}return Number(p[key])}
  function hasMetric(p,key){return p&&p[key]!==null&&p[key]!==undefined&&p[key]!==''&&Number.isFinite(numeric(p,key))}
  function configureMetrics(players){const minimum=Math.min(100,Math.max(20,Math.floor(players.length*.01))),coverage=new Map(METRICS.map(m=>[m.key,players.filter(p=>hasMetric(p,m.key)).length]));let metrics=METRICS.filter(m=>coverage.get(m.key)>=minimum),targets=players.filter(p=>metrics.every(m=>hasMetric(p,m.key)));while(metrics.length>5&&targets.length<minimum){metrics=metrics.filter(m=>m!==metrics.slice().sort((a,b)=>coverage.get(a.key)-coverage.get(b.key)||METRICS.indexOf(a)-METRICS.indexOf(b))[0]);targets=players.filter(p=>metrics.every(m=>hasMetric(p,m.key)))}return{metrics,targets}}
  function metricsFor(v){const keys=Array.isArray(v?.metricKeys)&&v.metricKeys.length?v.metricKeys:GAME_METRICS.map(m=>m.key);return keys.map(key=>METRICS.find(m=>m.key===key)).filter(Boolean)}
  function metricFor(v){return metricsFor(v)[v.round]}
  function format(v,key){if(key==='birth_date'){const d=new Date(v);if(Number.isNaN(d.getTime()))return'—';return String(d.getUTCDate()).padStart(2,'0')+'.'+String(d.getUTCMonth()+1).padStart(2,'0')+'.'+d.getUTCFullYear()}if(key==='height_cm')return v+' cm';if(key==='weight_kg')return v+' kg';if(key==='club_count')return v+' kulüp';if(key==='trophies')return v+' kupa';if(key==='career_goals')return v+' gol';if(key==='career_assists')return v+' asist';if(key==='career_appearances')return v+' maç';if(key==='peak_market_value_eur'){if(v>=1e6)return'€'+(v/1e6).toLocaleString('tr-TR',{maximumFractionDigits:1})+' M';if(v>=1e3)return'€'+(v/1e3).toLocaleString('tr-TR',{maximumFractionDigits:0})+' B';return'€'+Number(v).toLocaleString('tr-TR')}return String(v)}
  function diffText(d,key){if(key==='birth_date')return(d/365.2425).toLocaleString('tr-TR',{maximumFractionDigits:1})+' yıl fark';return format(d,key)+' fark'}
  function hostSelect(role,id,round){const g=hostGame;if(!g||g.phase!=='pick'||round!==g.round||g.picks[role])return;const p=BY_ID.get(id),m=metricFor(g);if(!m||!p||!hasMetric(p,m.key)||id===g.targetId||g.used[role].includes(id))return;g.picks[role]=id;g.revision++;if(g.picks.host&&g.picks.guest){resolveRound();S.localPass=false}else if(S.role==='local'&&role==='host'){localTurn='guest';S.localPass=true}broadcast();render()}
  function resolveRound(){const g=hostGame,m=metricFor(g),t=BY_ID.get(g.targetId),a=BY_ID.get(g.picks.host),b=BY_ID.get(g.picks.guest);if(!m||!t||!a||!b)return;const tv=numeric(t,m.key),av=numeric(a,m.key),bv=numeric(b,m.key),da=Math.abs(av-tv),db=Math.abs(bv-tv);let winner='draw';if(da<db)winner='host';else if(db<da)winner='guest';if(winner!=='draw')g.scores[winner]++;g.used.host.push(g.picks.host);g.used.guest.push(g.picks.guest);g.roundResult={winner,targetValue:t[m.key],hostValue:a[m.key],guestValue:b[m.key],hostDiff:da,guestDiff:db};g.phase='reveal';g.revision++}
  function advanceRound(round){const g=hostGame;if(!g||g.phase!=='reveal'||g.round!==round)return;if(g.round>=metricsFor(g).length-1){g.phase='final';g.revision++}else{g.round++;g.phase='pick';g.picks={host:null,guest:null};g.roundResult=null;g.revision++;S.search='';localTurn='host';S.localPass=false}broadcast();render()}
  function submit(id){const v=view();if(!v||v.phase!=='pick'||v.ownPick||S.pending||S.localPass)return;if(S.role==='local')hostSelect(localTurn,id,v.round);else if(S.role==='host')hostSelect('host',id,v.round);else if(guestConn&&guestConn.open){S.pending=true;guestConn.send({type:'select',playerId:id,round:v.round});clearTimeout(pendingTimer);pendingTimer=setTimeout(()=>{if(S.pending){S.pending=false;render()}},4000);render()}}
  function requestNext(v){if(S.role==='local'||S.role==='host')advanceRound(v.round);else if(guestConn&&guestConn.open)guestConn.send({type:'next',round:v.round})}
  function progress(v){const p=E('div','progress'),total=Math.max(1,metricsFor(v).length);p.setAttribute('aria-label','Tur ilerlemesi '+(v.round+1)+' / '+total);for(let i=0;i<total;i++)p.appendChild(E('div','pip'+(i<v.round?' done':i===v.round?' now':'')));app.appendChild(p)}
  function picked(v,role){if(v.phase==='reveal'||v.phase==='final')return v.picks&&BY_ID.get(v.picks[role]);if(role===v.role&&v.ownPick)return BY_ID.get(v.ownPick);return null}
  function initials(name){return String(name||'').trim().split(/\s+/).slice(0,2).map(part=>part.charAt(0)).join('').toLocaleUpperCase('tr-TR')||'—'}
  function statRow(label,value,cls){const row=E('div','statRow'+(cls?' '+cls:''));row.append(E('span','statLabel',esc(label)),E('b','statValue',esc(value)));return row}
  function arena(v,target,m){const a=E('div','arena');a.setAttribute('aria-label','Tur seçimleri');['host','target','guest'].forEach(role=>{const targetSlot=role==='target',s=E('section','slot role-'+role+(targetSlot?' target':'')),label=targetSlot?'HEDEF':v.players[role];s.appendChild(E('div','who',esc(label)));if(targetSlot){s.append(E('div','slotMonogram',esc(initials(target.name))),E('div','name',esc(target.name)));const stats=E('div','slotStats');stats.appendChild(statRow(v.phase==='reveal'?'DEĞER':'DURUM',v.phase==='reveal'?format(target[m.key],m.key):'HEDEF OYUNCU','targetValue'));s.appendChild(stats)}else{const player=picked(v,role),own=role===v.role,done=own?!!v.ownPick:!!v.oppPicked;if(player){s.classList.add('has-selection');s.append(E('div','slotMonogram',esc(initials(player.name))),E('div','name',esc(player.name)));const stats=E('div','slotStats');if(v.phase==='reveal'){const r=v.roundResult,val=role==='host'?r.hostValue:r.guestValue,d=role==='host'?r.hostDiff:r.guestDiff;stats.append(statRow('DEĞER',format(val,m.key),'playerValue'),statRow('FARK',diffText(d,m.key),'difference'));if(r.winner===role)s.classList.add('win');if(r.winner==='draw')s.classList.add('draw')}else stats.appendChild(statRow('DURUM','SEÇİM KİLİTLİ','locked'));s.appendChild(stats)}else{s.classList.add(done?'is-locked':'is-waiting');s.append(E('div','slotMonogram',esc(role==='host'?'P1':'P2')),E('div','name',done?'GİZLİ SEÇİM':'BEKLİYOR'));const stats=E('div','slotStats');stats.appendChild(statRow('DURUM',done?'RAKİP SEÇTİ':'SEÇİM BEKLENİYOR',done?'locked':'waiting'));s.appendChild(stats)}}a.appendChild(s)});app.appendChild(a)}
  function normName(s){return String(s||'').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
  function picker(v,target){if(S.localPass)return renderPass(v);if(v.ownPick||S.pending){const waiting=E('div','statusBox pickWaiting',S.pending?'Seçimin kaydediliyor…':'Seçimin kilitlendi. Rakibin seçimi bekleniyor.');waiting.setAttribute('role','status');app.appendChild(waiting);return}const c=E('section','card pickerCard'),h=E('div','searchHead','<b>FUTBOLCU ARA</b><span>SEÇİM KİLİTLENİR</span>'),i=E('input','field');i.placeholder='Oyuncu ismi yaz…';i.autocomplete='off';i.value=S.search;i.setAttribute('aria-label','Futbolcu ara');const r=E('div','results');r.setAttribute('aria-live','polite');i.oninput=()=>{S.search=i.value;c.classList.toggle('has-query',!!i.value.trim());fillResults(r,v,target)};c.classList.toggle('has-query',!!i.value.trim());c.append(h,i,r);fillResults(r,v,target);app.appendChild(c)}
  function renderPass(v){const p=E('div','passCard');p.innerHTML='<div class="label">SEÇİM KAYDEDİLDİ</div><b>TELEFONU '+esc(v.players.guest.toUpperCase())+' OYUNCUSUNA VER</b><div class="hint">İlk oyuncunun seçimi gizlendi.</div>';p.appendChild(btn('DEVAM · OYUNCU 2',true,()=>{S.localPass=false;S.search='';render()}));app.appendChild(p)}
  function fillResults(box,v,target){box.innerHTML='';const q=normName(S.search.trim());if(!q){box.appendChild(E('div','statusBox','Oyuncu ismi yazdığında eşleşen futbolcular burada görünecek.'));return}const used=new Set(v.used||[]),m=metricFor(v);if(!m)return;let list=SEARCH_PLAYERS.filter(p=>p.id!==target.id&&!used.has(p.id)&&hasMetric(p,m.key)&&normName(p.name).includes(q));list.sort((a,b)=>{const an=normName(a.name),bn=normName(b.name),ae=an.startsWith(q)?1:0,be=bn.startsWith(q)?1:0;return be-ae||(b.recognition_score||0)-(a.recognition_score||0)});list=list.slice(0,14);if(!list.length){box.appendChild(E('div','statusBox','Bu parametre için verisi olan eşleşen oyuncu bulunamadı.'));return}list.forEach(p=>{const b=E('button','playerBtn');b.type='button';b.innerHTML='<b>'+esc(p.name)+'</b><span class="chooseCopy">SEÇ</span>';b.setAttribute('aria-label',p.name+' oyuncusunu seç');b.onclick=()=>submit(p.id);box.appendChild(b)})}
  function reveal(v,target,m){const r=v.roundResult;if(!r)return;const panel=E('section','card roundResult');panel.setAttribute('aria-live','polite');panel.appendChild(E('div','revealTitle','TUR SONUCU'));const text=r.winner==='draw'?'BERABERE':(r.winner==='host'?v.players.host:v.players.guest)+' BU TURU KAZANDI';panel.appendChild(E('div','winnerText'+(r.winner==='draw'?' draw':''),esc(text)));const rows=E('div','resultRows');const row=(label,value,difference,kind)=>{const item=E('div','resultRow '+kind);item.append(E('span','resultName',esc(label)),E('b','resultValue',esc(value)));if(difference)item.appendChild(E('span','resultDiff',esc(difference)));return item};rows.append(row(v.players.host,format(r.hostValue,m.key),diffText(r.hostDiff,m.key),'host'),row('HEDEF',format(r.targetValue,m.key),'','target'),row(v.players.guest,format(r.guestValue,m.key),diffText(r.guestDiff,m.key),'guest'));panel.appendChild(rows);panel.appendChild(btn(v.round===metricsFor(v).length-1?'SONUCU GÖR':'SONRAKİ PARAMETRE',true,()=>requestNext(v)));app.appendChild(panel)}
  function activeConn(){return S.role==='host'?hostConn:S.role==='guest'?guestConn:null}
  function ownRole(){return S.role==='host'?'host':'guest'}
  function sendPacket(packet){const c=activeConn();if(c&&c.open){try{c.send(packet);return true}catch{}}auxQueue.push(packet);if(auxQueue.length>20)auxQueue.shift();return false}
  function flushAux(){const c=activeConn();if(!c||!c.open)return;const q=auxQueue.splice(0);q.forEach(x=>{try{c.send(x)}catch{auxQueue.push(x)}})}
  function sendAux(kind,text){text=String(text||'').trim().slice(0,160);if(!text||S.role==='local')return;const role=ownRole(),name=view()?.players?.[role]||S.name||role;const packet={type:kind,text,id:Date.now()+'-'+Math.random().toString(36).slice(2,7)};chatLog.push({id:packet.id,role:'self',name,text,kind});chatLog=chatLog.slice(-30);sendPacket(packet);S.chatDraft='';refreshChat()}
  function receiveAux(from,m){const v=view(),name=v?.players?.[from]||(from==='host'?'Oyuncu 1':'Oyuncu 2'),text=String(m.text||'').trim().slice(0,160);if(!text)return;chatLog.push({id:m.id||Date.now()+Math.random(),role:'other',name,text,kind:m.type});chatLog=chatLog.slice(-30);refreshChat()}
  function refreshChat(){const box=document.getElementById('ctChatLog');if(!box)return;box.innerHTML='';chatLog.forEach(m=>{const d=E('div','chatMsg '+m.role);d.innerHTML='<span class="chatWho">'+esc(m.name)+'</span>'+esc(m.text);box.appendChild(d)});box.scrollTop=box.scrollHeight;const i=document.getElementById('ctChatInput');if(i)i.value=S.chatDraft}
  function renderChat(v){if(S.role==='local')return;const c=E('div','chatCard');c.innerHTML='<div class="chatTitle"><span>MAÇ SOHBETİ</span><span class="connectionDot">'+((activeConn()&&activeConn().open)?'● BAĞLI':'○ BAĞLANIYOR')+'</span></div>';const log=E('div','chatLog');log.id='ctChatLog';const row=E('div','chatRow'),i=E('input','field chatInput');i.id='ctChatInput';i.placeholder='Mesaj yaz…';i.value=S.chatDraft;i.maxLength=160;i.oninput=()=>S.chatDraft=i.value;i.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();sendAux('chat',i.value)}};const send=btn('GÖNDER',true,()=>sendAux('chat',i.value));send.classList.add('chatSend');row.append(i,send);const emojis=E('div','emojiRow');['😂','🔥','😎','👏','🤯','❤️'].forEach(x=>{const b=E('button','emojiBtn',x);b.type='button';b.onclick=()=>sendAux('emoji',x);emojis.appendChild(b)});c.append(log,row,emojis);app.appendChild(c);refreshChat()}
  function renderGame(){const v=view();if(!v){brand('Oyun durumu bekleniyor…');app.appendChild(E('div','card center','<div class="spinner"></div>'));return}document.body.dataset.ctPhase=v.phase||'';document.body.dataset.ctRound=String(v.round||0);if(v.phase==='final')return final(v);brand(S.role==='local'?'Tek telefon · sırayla seçim':'Hedef futbolcuya en yakın kariyeri seç');const metrics=metricsFor(v),m=metricFor(v),target=BY_ID.get(v.targetId);if(!target||!m){app.appendChild(E('div','error','Hedef oyuncu verisi bulunamadı.'));return}const statusFor=role=>{if(v.phase==='reveal'){if(v.roundResult?.winner==='draw')return'BERABERE';return v.roundResult?.winner===role?'TUR GALİBİ':'TUR TAMAMLANDI'}const own=role===v.role,done=own?!!v.ownPick:!!v.oppPicked;return done?'SEÇİM KİLİTLİ':own?'SENİN SIRAN':'BEKLİYOR'};const scoreCard=role=>'<div class="score '+(role==='guest'?'right':'')+'"><div class="n">'+esc(v.players[role])+'</div><div class="p"><b class="scorePoints">'+v.scores[role]+'</b><span class="scoreState">'+esc(statusFor(role))+'</span></div></div>';const s=E('div','scorebar');s.innerHTML=scoreCard('host')+'<div class="roundBadge"><span>TUR</span><b>'+(v.round+1)+'/'+metrics.length+'</b></div>'+scoreCard('guest');app.appendChild(s);const mt=E('div','metricTitle','<span>PARAMETRE</span><b>'+esc(m.label)+'</b>');app.appendChild(mt);progress(v);arena(v,target,m);if(v.phase==='pick')picker(v,target);else reveal(v,target,m);renderChat(v)}
  function final(v){brand(metricsFor(v).length+' parametre tamamlandı');const c=E('div','card center'),hs=v.scores.host,gs=v.scores.guest,title=hs===gs?'OYUN BERABERE':hs>gs?v.players.host+' KAZANDI':v.players.guest+' KAZANDI';c.append(E('div','label','FİNAL'),E('div','finalTitle',esc(title.toUpperCase())),E('div','finalScore',hs+' — '+gs));const t=BY_ID.get(v.targetId);if(t)c.appendChild(E('div','hint','Hedef futbolcu: <b>'+esc(t.name)+'</b>'));app.appendChild(c);if(S.role==='local')app.appendChild(btn('YENİ OYUN',true,()=>startGame('Oyuncu 2')));else if(S.role==='host')app.appendChild(btn('AYNI ODAYLA YENİ OYUN',true,()=>startGame(hostGame.players.guest)));else app.appendChild(E('div','statusBox','Oda sahibi yeni oyun başlatabilir.'));renderChat(v);app.appendChild(btn('YAN OYUNLARA DÖN',false,()=>{cleanup();location.href='../index.html'}))}
  async function init(){injectCss();render();try{const response=await fetch('../data/master/transfermarkt-players.json',{cache:'no-store'});if(!response.ok)throw new Error('data');const master=await response.json(),all=new Map();master.forEach(p=>{if(p&&p.id&&p.name)all.set(Number(p.id),p)});PLAYERS=[...all.values()];SEARCH_PLAYERS=PLAYERS;BY_ID=all;const configured=configureMetrics(PLAYERS);GAME_METRICS=configured.metrics;TARGET_PLAYERS=configured.targets;if(GAME_METRICS.length<5||TARGET_PLAYERS.length<20||SEARCH_PLAYERS.length<100)throw new Error('empty');S.screen='menu';render()}catch(e){console.error(e);app.innerHTML='';top();brand('Oyuncu verileri yüklenemedi');app.appendChild(E('div','card center','<div class="error">Transfermarkt master havuzu açılamadı. Biraz sonra tekrar dene.</div>'))}}
  window.addEventListener('beforeunload',cleanup);init();
})();
