import {initializeApp,getApp,getApps} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js';
import {getAuth,onAuthStateChanged,signInAnonymously} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import {getDatabase,get,onDisconnect,onValue,ref,remove,runTransaction,serverTimestamp,set,update} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-database.js';

const CONFIG={apiKey:'AIzaSyBLpXHGGTHXykKrnu8_Hv1i71oc3tpTNvY',authDomain:'neonxi.firebaseapp.com',databaseURL:'https://neonxi-default-rtdb.europe-west1.firebasedatabase.app',projectId:'neonxi',storageBucket:'neonxi.firebasestorage.app',messagingSenderId:'667191549799',appId:'1:667191549799:web:1e40feacbee09ed7f3d9c2'};
const MODES={draft:{label:'NEON XI Draft',path:'index.html',code:'alpha6',matchable:true},xox:{label:'Futbol XOX',path:'side-games/football-xox/index.html',code:'numeric4',matchable:true},twin:{label:'Career Twin',path:'side-games/career-twin/index.html',code:'numeric4',matchable:true},imposter:{label:'Futbol Imposter',path:'side-games/futbol-imposter.html',code:'numeric4',matchable:false}};
const base=new URL('../',import.meta.url),app=getApps().length?getApp():initializeApp(CONFIG),auth=getAuth(app),db=getDatabase(app);
const state={user:null,profile:null,friends:{},requests:{},invites:{},party:null,partyId:'',queueOff:null,partyOff:null,launchNonce:'',tab:'play'};
let statusEl,shade,button;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/[^a-z0-9_]/g,'').slice(0,20);
const clean=s=>String(s||'').replace(/[^A-Za-zÇĞİÖŞÜçğıöşü0-9_]/g,'').slice(0,20);
const modeUrl=(mode,params={})=>{const u=new URL(MODES[mode].path,base);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v));return u.href};
const codeFor=mode=>MODES[mode].code==='numeric4'?String(Math.floor(1000+Math.random()*9000)):[...Array(6)].map(()=> 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[Math.floor(Math.random()*32)]).join('');
function message(text,error=false){if(!statusEl)return;statusEl.textContent=text;statusEl.classList.toggle('error',error)}
async function ready(){if(auth.currentUser){state.user=auth.currentUser;return state.user}return new Promise((resolve,reject)=>{const off=onAuthStateChanged(auth,u=>{if(u){off();state.user=u;resolve(u)}});signInAnonymously(auth).catch(reject)})}
function shell(){
  document.head.insertAdjacentHTML('beforeend',`<link rel="stylesheet" href="${new URL('neon-social.css',import.meta.url).href}">`);
  button=document.createElement('button');button.className='nx-social-launch';button.type='button';button.textContent='SOSYAL';button.dataset.count='0';button.onclick=()=>open('play');document.body.appendChild(button);
  shade=document.createElement('div');shade.className='nx-social-shade';shade.innerHTML=`<section class="nx-social-panel" role="dialog" aria-modal="true" aria-label="NEON XI Sosyal"><div class="nx-social-head"><strong>NEON XI SOSYAL</strong><button class="nx-social-close" type="button" aria-label="Kapat">×</button></div><div class="nx-social-tabs"><button data-tab="play">OYNA</button><button data-tab="friends">ARKADAŞLAR</button><button data-tab="party">PARTİ</button></div><div class="nx-social-view" data-view="play"></div><div class="nx-social-view" data-view="friends"></div><div class="nx-social-view" data-view="party"></div><div class="nx-social-status" role="status"></div></section>`;document.body.appendChild(shade);statusEl=shade.querySelector('.nx-social-status');shade.querySelector('.nx-social-close').onclick=close;shade.addEventListener('click',e=>{if(e.target===shade)close();const tab=e.target.closest('[data-tab]');if(tab)render(tab.dataset.tab)});
}
function open(tab='play'){shade.classList.add('open');render(tab)}function close(){shade.classList.remove('open')}
function requireProfile(){if(state.profile)return true;message('Önce benzersiz oyuncu adını oluştur.',true);render('friends');return false}
function render(tab=state.tab){state.tab=tab;shade.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));shade.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===tab));renderPlay();renderFriends();renderParty()}
function renderPlay(){const v=shade.querySelector('[data-view="play"]');v.innerHTML=`<div class="nx-social-choice"><button class="nx-social-btn primary" data-act="party-play">ARKADAŞLARLA OYNA</button><button class="nx-social-btn" data-act="match">RAKİP ARA</button></div><div class="nx-social-card"><label class="nx-social-label">OYUN MODU</label><select class="nx-social-select" id="nxMode">${Object.entries(MODES).map(([k,m])=>`<option value="${k}">${m.label}</option>`).join('')}</select></div><div class="nx-social-card"><span class="nx-social-label">ODA KODU · YEDEK YÖNTEM</span><div class="nx-social-muted">Her oyunun mevcut “oda oluştur / kodla katıl” ekranı korunuyor.</div><button class="nx-social-btn" data-act="room-code">ODA KODU EKRANINA GİT</button></div>`;v.querySelector('[data-act="party-play"]').onclick=()=>{if(!requireProfile())return;render('party')};v.querySelector('[data-act="match"]').onclick=()=>startMatch(v.querySelector('#nxMode').value);v.querySelector('[data-act="room-code"]').onclick=()=>{const mode=v.querySelector('#nxMode').value;close();location.href=modeUrl(mode,{nxRoomCode:'1'})}}
function renderFriends(){const v=shade.querySelector('[data-view="friends"]');if(!state.profile){v.innerHTML=`<div class="nx-social-card"><label class="nx-social-label">BENZERSİZ OYUNCU ADI</label><div class="nx-social-row"><input class="nx-social-input" id="nxUsername" maxlength="20" placeholder="oyuncu_adi"><button class="nx-social-btn primary" data-act="claim">OLUŞTUR</button></div><div class="nx-social-muted">3–20 karakter; harf, rakam ve alt çizgi.</div></div>`;v.querySelector('[data-act="claim"]').onclick=()=>claim(v.querySelector('#nxUsername').value);return}const req=Object.entries(state.requests||{}),friends=Object.entries(state.friends||{});v.innerHTML=`<div class="nx-social-card"><span class="nx-social-label">OYUNCU ADIN</span><b>@${esc(state.profile.username)}</b></div><div class="nx-social-card"><label class="nx-social-label">İSİMLE ARKADAŞ ARA</label><div class="nx-social-row"><input class="nx-social-input" id="nxFind" placeholder="tam oyuncu adı"><button class="nx-social-btn" data-act="find">ARA</button></div><div id="nxFindResult"></div></div><div class="nx-social-card"><span class="nx-social-label">İSTEKLER (${req.length})</span><div class="nx-social-list">${req.length?req.map(([uid,x])=>item(uid,x.username,'request')).join(''):'<span class="nx-social-muted">Bekleyen istek yok.</span>'}</div></div><div class="nx-social-card"><span class="nx-social-label">ARKADAŞLAR (${friends.length})</span><div class="nx-social-list">${friends.length?friends.map(([uid,x])=>item(uid,x.username,'friend')).join(''):'<span class="nx-social-muted">Henüz arkadaş eklenmedi.</span>'}</div></div>`;v.querySelector('[data-act="find"]').onclick=()=>findPlayer(v.querySelector('#nxFind').value);v.querySelectorAll('[data-accept]').forEach(b=>b.onclick=()=>acceptFriend(b.dataset.accept));v.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>remove(ref(db,`social/friendRequests/${state.user.uid}/${b.dataset.reject}`)));v.querySelectorAll('[data-invite]').forEach(b=>b.onclick=()=>invite(b.dataset.invite))}
function item(uid,name,type){return `<div class="nx-social-item"><div><b>@${esc(name)}</b><br><small>${type==='friend'?'Arkadaş':'Arkadaşlık isteği'}</small></div><div class="nx-social-actions">${type==='friend'?`<button class="nx-social-btn" data-invite="${uid}">PARTİYE ÇAĞIR</button>`:`<button class="nx-social-btn primary" data-accept="${uid}">KABUL</button><button class="nx-social-btn nx-social-danger" data-reject="${uid}">RED</button>`}</div></div>`}
function renderParty(){const v=shade.querySelector('[data-view="party"]'),inv=Object.entries(state.invites||{});if(!state.profile){v.innerHTML='<div class="nx-social-card nx-social-muted">Parti için önce Arkadaşlar sekmesinden oyuncu adı oluştur.</div>';return}if(!state.party){v.innerHTML=`${inv.map(([id,x])=>`<div class="nx-social-card"><b>@${esc(x.fromName)}</b> seni partisine çağırdı.<div class="nx-social-actions"><button class="nx-social-btn primary" data-party-accept="${id}">KABUL</button><button class="nx-social-btn" data-party-reject="${id}">RED</button></div></div>`).join('')}<button class="nx-social-btn primary" data-act="create-party">YENİ PARTİ KUR</button>`;v.querySelector('[data-act="create-party"]').onclick=createParty;v.querySelectorAll('[data-party-accept]').forEach(b=>b.onclick=()=>acceptParty(b.dataset.partyAccept));v.querySelectorAll('[data-party-reject]').forEach(b=>b.onclick=()=>remove(ref(db,`social/partyInvites/${state.user.uid}/${b.dataset.partyReject}`)));return}const members=Object.entries(state.party.members||{}),leader=state.party.leaderUid===state.user.uid;v.innerHTML=`<div class="nx-social-card"><span class="nx-social-label">KALICI PARTİ</span><span class="nx-social-pill">${leader?'LİDER':'ÜYE'}</span><div class="nx-social-list">${members.map(([uid,x])=>`<div class="nx-social-item"><b>@${esc(x.username)}</b>${uid===state.party.leaderUid?'<small>Lider</small>':''}</div>`).join('')}</div></div>${leader?`<div class="nx-social-card"><label class="nx-social-label">PARTİYLE MODA GEÇ</label><select class="nx-social-select" id="nxPartyMode">${Object.entries(MODES).map(([k,m])=>`<option value="${k}">${m.label}</option>`).join('')}</select><button class="nx-social-btn primary" data-act="launch-party">PARTİYİ OYUNA GÖTÜR</button></div>`:'<div class="nx-social-card nx-social-muted">Parti lideri oyun seçtiğinde herkes otomatik olarak aynı moda geçer.</div>'}<button class="nx-social-btn nx-social-danger" data-act="leave-party">PARTİDEN AYRIL</button>`;v.querySelector('[data-act="launch-party"]')?.addEventListener('click',()=>launchParty(v.querySelector('#nxPartyMode').value));v.querySelector('[data-act="leave-party"]').onclick=leaveParty}
async function claim(raw){const username=clean(raw),key=norm(username);if(key.length<3){message('Oyuncu adı en az 3 karakter olmalı.',true);return}try{const result=await runTransaction(ref(db,`social/usernames/${key}`),v=>v&&v!==state.user.uid?undefined:state.user.uid,{applyLocally:false});if(!result.committed)throw new Error('Bu oyuncu adı kullanılıyor.');await update(ref(db),{[`social/profiles/${state.user.uid}`]:{username,key,updatedAt:serverTimestamp()}});message(`@${username} oluşturuldu.`)}catch(e){message(e.message||'Oyuncu adı oluşturulamadı.',true)}}
async function findPlayer(raw){const key=norm(raw),box=shade.querySelector('#nxFindResult');if(!key){message('Aranacak oyuncu adını yaz.',true);return}const s=await get(ref(db,`social/usernames/${key}`)),uid=s.val();if(!uid||uid===state.user.uid){box.innerHTML='<div class="nx-social-muted">Oyuncu bulunamadı.</div>';return}const p=(await get(ref(db,`social/profiles/${uid}`))).val();box.innerHTML=`<div class="nx-social-item"><b>@${esc(p?.username||raw)}</b><button class="nx-social-btn primary" data-add="${uid}">EKLE</button></div>`;box.querySelector('[data-add]').onclick=()=>sendFriend(uid,p.username)}
async function sendFriend(uid,username){await set(ref(db,`social/friendRequests/${uid}/${state.user.uid}`),{username:state.profile.username,createdAt:serverTimestamp()});message(`@${username} arkadaşlık isteği gönderildi.`)}
async function acceptFriend(uid){const req=state.requests[uid];await update(ref(db),{[`social/friends/${state.user.uid}/${uid}`]:{username:req.username,since:serverTimestamp()},[`social/friends/${uid}/${state.user.uid}`]:{username:state.profile.username,since:serverTimestamp()},[`social/friendRequests/${state.user.uid}/${uid}`]:null});message(`@${req.username} arkadaşlara eklendi.`)}
async function createParty(){const id=`p_${state.user.uid.slice(0,8)}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,6)}`;await update(ref(db),{[`social/parties/${id}`]:{leaderUid:state.user.uid,createdAt:serverTimestamp(),members:{[state.user.uid]:{username:state.profile.username,joinedAt:serverTimestamp()}}},[`social/userParty/${state.user.uid}`]:id});message('Kalıcı parti kuruldu.');return id}
async function invite(uid){const partyId=state.party?.members?state.partyId:await createParty();await set(ref(db,`social/partyInvites/${uid}/${partyId}`),{fromUid:state.user.uid,fromName:state.profile.username,createdAt:serverTimestamp()});message('Parti daveti gönderildi.');render('party')}
async function acceptParty(id){const ps=(await get(ref(db,`social/parties/${id}`))).val();if(!ps)throw new Error('Parti artık mevcut değil.');await update(ref(db),{[`social/parties/${id}/members/${state.user.uid}`]:{username:state.profile.username,joinedAt:serverTimestamp()},[`social/userParty/${state.user.uid}`]:id,[`social/partyInvites/${state.user.uid}/${id}`]:null});message('Partiye katıldın.')}
async function leaveParty(){if(!state.partyId)return;const id=state.partyId,leader=state.party.leaderUid===state.user.uid,members=Object.keys(state.party.members||{}).filter(x=>x!==state.user.uid);const changes={[`social/userParty/${state.user.uid}`]:null,[`social/parties/${id}/members/${state.user.uid}`]:null};if(leader&&members.length)changes[`social/parties/${id}/leaderUid`]=members[0];if(!members.length)changes[`social/parties/${id}`]=null;await update(ref(db),changes);message('Partiden ayrıldın.')}
async function launchParty(mode){const nonce=`${Date.now()}_${Math.random().toString(36).slice(2,7)}`,members=Object.keys(state.party.members||{});if(MODES[mode].matchable&&members.length!==2){message('Bu 1v1 mod için partide tam iki oyuncu olmalı.',true);return}const launch={mode,nonce,at:serverTimestamp()};if(MODES[mode].matchable){launch.roomCode=codeFor(mode);launch.roles={[state.party.leaderUid]:'host',[members.find(uid=>uid!==state.party.leaderUid)]:'guest'}}await set(ref(db,`social/parties/${state.partyId}/launch`),launch);navigateParty(launch)}
function navigateParty(launch){const {mode,nonce}=launch||{};if(!mode||!nonce||state.launchNonce===nonce||sessionStorage.getItem('nxPartyLaunch')===nonce)return;const params={nxParty:state.partyId};if(launch.roomCode&&launch.roles?.[state.user.uid])Object.assign(params,{nxAuto:'1',nxRole:launch.roles[state.user.uid],nxCode:launch.roomCode,nxName:state.profile?.username||state.party?.members?.[state.user.uid]?.username||'NEON Oyuncu'});const target=modeUrl(mode,params);if(location.pathname===new URL(target).pathname&&new URLSearchParams(location.search).get('nxParty')===state.partyId){sessionStorage.setItem('nxPartyLaunch',nonce);return}state.launchNonce=nonce;sessionStorage.setItem('nxPartyLaunch',nonce);location.href=target}
async function startMatch(mode){if(!requireProfile())return;if(!MODES[mode]?.matchable){message('Bu mod grup partisiyle oynanır; 1v1 rakip arama Draft, XOX ve Career Twin için açık.',true);return}message('Uygun rakip aranıyor…');const path=`social/matchQueues/${mode}`,uid=state.user.uid,joinedAt=Date.now();await set(ref(db,`${path}/${uid}`),{uid,username:state.profile.username,status:'waiting',joinedAt});onDisconnect(ref(db,`${path}/${uid}`)).remove().catch(()=>{});await runTransaction(ref(db,path),q=>{q=q||{};if(q[uid]?.status!=='waiting')return q;const other=Object.values(q).filter(x=>x&&x.uid!==uid&&x.status==='waiting'&&joinedAt-Number(x.joinedAt||0)<60000).sort((a,b)=>a.joinedAt-b.joinedAt)[0];if(!other)return q;const host=other.joinedAt<=joinedAt?other.uid:uid,matchId=`m_${Math.min(joinedAt,other.joinedAt)}_${host.slice(0,7)}`,roomCode=codeFor(mode);q[uid]={...q[uid],status:'matched',matchId,roomCode,role:uid===host?'host':'guest',opponentUid:other.uid};q[other.uid]={...q[other.uid],status:'matched',matchId,roomCode,role:other.uid===host?'host':'guest',opponentUid:uid};return q},{applyLocally:false});if(state.queueOff)state.queueOff();state.queueOff=onValue(ref(db,`${path}/${uid}`),s=>{const x=s.val();if(x?.status==='matched'){state.queueOff?.();state.queueOff=null;message('Rakip bulundu. Maç lobisine giriliyor…');setTimeout(()=>{location.href=modeUrl(mode,{nxAuto:'1',nxRole:x.role,nxCode:x.roomCode,nxName:state.profile.username,nxMatch:x.matchId})},350)}});renderSearching(mode)}
function renderSearching(mode){const v=shade.querySelector('[data-view="play"]');v.innerHTML=`<div class="nx-social-searching"><b>${esc(MODES[mode].label)}</b><div>Rakip aranıyor…</div><button class="nx-social-btn nx-social-danger" data-act="cancel">ARAMAYI İPTAL ET</button></div>`;v.querySelector('[data-act="cancel"]').onclick=async()=>{state.queueOff?.();state.queueOff=null;await remove(ref(db,`social/matchQueues/${mode}/${state.user.uid}`));message('Arama iptal edildi.');render('play')}}
  async function bind(){await ready();onValue(ref(db,`social/profiles/${state.user.uid}`),s=>{state.profile=s.val();render()});onValue(ref(db,`social/friends/${state.user.uid}`),s=>{state.friends=s.val()||{};render()});onValue(ref(db,`social/friendRequests/${state.user.uid}`),s=>{state.requests=s.val()||{};button.dataset.count=String(Object.keys(state.requests).length+Object.keys(state.invites).length);render()});onValue(ref(db,`social/partyInvites/${state.user.uid}`),s=>{state.invites=s.val()||{};button.dataset.count=String(Object.keys(state.requests).length+Object.keys(state.invites).length);render()});onValue(ref(db,`social/userParty/${state.user.uid}`),s=>{state.partyId=s.val()||'';state.partyOff?.();state.party=null;if(!state.partyId){render();return}state.partyOff=onValue(ref(db,`social/parties/${state.partyId}`),p=>{state.party=p.val();const l=state.party?.launch;if(l?.mode&&l?.nonce)navigateParty(l);render()})})}
shell();bind().catch(e=>message(`Sosyal bağlantı kurulamadı: ${e.message}`,true));
window.NEON_SOCIAL={open,close,modes:MODES,get profile(){return state.profile},get party(){return state.party}};
document.addEventListener('click',e=>{const b=e.target.closest('[data-neon-social]');if(b){e.preventDefault();open(b.dataset.neonSocial||'play')}});
